type PrinterLocale = "fr" | "ht" | "pt" | "es" | "de" | "zh-CN" | "ru" | "ja" | "ko" | "id";

const keys = [
  "Printers", "The clinic server manages the physical printer. Desktop, web and mobile clients all print through this secure local connection.",
  "No default printer", "Search on Linux or enter the Bluetooth COM port shown by Windows.", "Print test page", "Search for printers", "Reconnect and test",
  "No compatible printer found.", "Printer search failed", "Default printer saved", "Could not save printer", "Test page printed", "Test print failed",
  "Default printer", "Set as default", "RFCOMM channel not detected", "Windows Bluetooth COM port", "Pair the printer in Windows Settings, then enter its outgoing COM port.", "Save port",
  "Recent print attempts", "Technical history only; no medical details are stored here.", "Printer", "Receipt", "No print attempts yet", "Print a test page or a POS receipt to verify the connection.",
  "Payment completed", "was saved successfully. Printing is independent and can be retried safely.", "Reprint receipt", "Print receipt", "New sale", "Thermal receipt printed",
  "The payment is saved, but the printer is unavailable.", "Printer not configured", "Printing…", "Receipt footer", "Thank you for your trust.",
  "ready", "connected", "available", "offline", "configured", "printed", "failed",
] as const;

const values: Record<PrinterLocale, readonly string[]> = {
  fr: ["Imprimantes", "Le serveur de la clinique gère l’imprimante physique. Les clients ordinateur, web et mobile impriment tous via cette connexion locale sécurisée.", "Aucune imprimante par défaut", "Recherchez sous Linux ou saisissez le port COM Bluetooth affiché par Windows.", "Imprimer une page de test", "Rechercher des imprimantes", "Reconnecter et tester", "Aucune imprimante compatible trouvée.", "Échec de la recherche d’imprimantes", "Imprimante par défaut enregistrée", "Impossible d’enregistrer l’imprimante", "Page de test imprimée", "Échec de l’impression de test", "Imprimante par défaut", "Définir par défaut", "Canal RFCOMM non détecté", "Port COM Bluetooth Windows", "Associez l’imprimante dans les Paramètres Windows, puis saisissez son port COM sortant.", "Enregistrer le port", "Tentatives d’impression récentes", "Historique technique uniquement ; aucune information médicale n’est enregistrée ici.", "Imprimante", "Reçu", "Aucune tentative d’impression", "Imprimez une page de test ou un reçu PDV pour vérifier la connexion.", "Paiement effectué", "a été enregistré. L’impression est indépendante et peut être relancée en toute sécurité.", "Réimprimer le reçu", "Imprimer le reçu", "Nouvelle vente", "Reçu thermique imprimé", "Le paiement est enregistré, mais l’imprimante est indisponible.", "Imprimante non configurée", "Impression…", "Pied de page du reçu", "Merci pour votre confiance.", "prête", "connectée", "disponible", "hors ligne", "configurée", "imprimé", "échoué"],
  ht: ["Enprimant", "Sèvè klinik la jere enprimant fizik la. Òdinatè, entènèt ak aparèy mobil yo enprime atravè koneksyon lokal sekirize sa a.", "Pa gen enprimant pa defo", "Chèche sou Linux oswa antre pò COM Bluetooth Windows montre a.", "Enprime paj tès", "Chèche enprimant", "Rekonekte epi teste", "Pa jwenn enprimant konpatib.", "Rechèch enprimant lan echwe", "Enprimant pa defo anrejistre", "Pa t kapab anrejistre enprimant lan", "Paj tès la enprime", "Enpresyon tès la echwe", "Enprimant pa defo", "Mete kòm pa defo", "Kanal RFCOMM pa detekte", "Pò COM Bluetooth Windows", "Konekte enprimant lan nan Paramèt Windows, epi antre pò COM sòti li a.", "Anrejistre pò a", "Dènye tantativ enpresyon", "Se sèlman istwa teknik; pa gen detay medikal ki estoke isit la.", "Enprimant", "Resi", "Pa gen tantativ enpresyon ankò", "Enprime yon paj tès oswa yon resi POS pou verifye koneksyon an.", "Peman fèt", "anrejistre avèk siksè. Enpresyon an endepandan epi ou ka rekòmanse li san danje.", "Re-enprime resi", "Enprime resi", "Nouvo vant", "Resi tèmik enprime", "Peman an anrejistre, men enprimant lan pa disponib.", "Enprimant pa konfigire", "Ap enprime…", "Pye paj resi", "Mèsi pou konfyans ou.", "pare", "konekte", "disponib", "dekonekte", "konfigire", "enprime", "echwe"],
  pt: ["Impressoras", "O servidor da clínica gerencia a impressora física. Clientes desktop, web e móveis imprimem por esta conexão local segura.", "Nenhuma impressora padrão", "Pesquise no Linux ou informe a porta COM Bluetooth exibida pelo Windows.", "Imprimir página de teste", "Procurar impressoras", "Reconectar e testar", "Nenhuma impressora compatível encontrada.", "Falha ao procurar impressoras", "Impressora padrão salva", "Não foi possível salvar a impressora", "Página de teste impressa", "Falha na impressão de teste", "Impressora padrão", "Definir como padrão", "Canal RFCOMM não detectado", "Porta COM Bluetooth do Windows", "Emparelhe a impressora nas Configurações do Windows e informe a porta COM de saída.", "Salvar porta", "Tentativas de impressão recentes", "Somente histórico técnico; nenhum dado médico é armazenado aqui.", "Impressora", "Recibo", "Nenhuma tentativa de impressão", "Imprima uma página de teste ou recibo do PDV para verificar a conexão.", "Pagamento concluído", "foi salvo com sucesso. A impressão é independente e pode ser repetida com segurança.", "Reimprimir recibo", "Imprimir recibo", "Nova venda", "Recibo térmico impresso", "O pagamento foi salvo, mas a impressora está indisponível.", "Impressora não configurada", "Imprimindo…", "Rodapé do recibo", "Obrigado pela sua confiança.", "pronta", "conectada", "disponível", "offline", "configurada", "impresso", "falhou"],
  es: ["Impresoras", "El servidor de la clínica administra la impresora física. Los clientes de escritorio, web y móvil imprimen mediante esta conexión local segura.", "Sin impresora predeterminada", "Busque en Linux o introduzca el puerto COM Bluetooth mostrado por Windows.", "Imprimir página de prueba", "Buscar impresoras", "Reconectar y probar", "No se encontró una impresora compatible.", "Error al buscar impresoras", "Impresora predeterminada guardada", "No se pudo guardar la impresora", "Página de prueba impresa", "Error en la impresión de prueba", "Impresora predeterminada", "Establecer como predeterminada", "Canal RFCOMM no detectado", "Puerto COM Bluetooth de Windows", "Empareje la impresora en Configuración de Windows e introduzca su puerto COM de salida.", "Guardar puerto", "Intentos de impresión recientes", "Solo historial técnico; aquí no se guardan datos médicos.", "Impresora", "Recibo", "Aún no hay intentos de impresión", "Imprima una página de prueba o un recibo del POS para verificar la conexión.", "Pago completado", "se guardó correctamente. La impresión es independiente y se puede reintentar de forma segura.", "Reimprimir recibo", "Imprimir recibo", "Nueva venta", "Recibo térmico impreso", "El pago está guardado, pero la impresora no está disponible.", "Impresora no configurada", "Imprimiendo…", "Pie del recibo", "Gracias por su confianza.", "lista", "conectada", "disponible", "sin conexión", "configurada", "impreso", "fallido"],
  de: ["Drucker", "Der Klinikserver verwaltet den physischen Drucker. Desktop-, Web- und Mobilgeräte drucken über diese sichere lokale Verbindung.", "Kein Standarddrucker", "Unter Linux suchen oder den von Windows angezeigten Bluetooth-COM-Port eingeben.", "Testseite drucken", "Nach Druckern suchen", "Neu verbinden und testen", "Kein kompatibler Drucker gefunden.", "Druckersuche fehlgeschlagen", "Standarddrucker gespeichert", "Drucker konnte nicht gespeichert werden", "Testseite gedruckt", "Testdruck fehlgeschlagen", "Standarddrucker", "Als Standard festlegen", "RFCOMM-Kanal nicht erkannt", "Windows-Bluetooth-COM-Port", "Koppeln Sie den Drucker in den Windows-Einstellungen und geben Sie seinen ausgehenden COM-Port ein.", "Port speichern", "Letzte Druckversuche", "Nur technischer Verlauf; hier werden keine medizinischen Daten gespeichert.", "Drucker", "Beleg", "Noch keine Druckversuche", "Drucken Sie eine Testseite oder einen POS-Beleg, um die Verbindung zu prüfen.", "Zahlung abgeschlossen", "wurde erfolgreich gespeichert. Der Druck ist unabhängig und kann sicher wiederholt werden.", "Beleg erneut drucken", "Beleg drucken", "Neuer Verkauf", "Thermobeleg gedruckt", "Die Zahlung ist gespeichert, aber der Drucker ist nicht verfügbar.", "Drucker nicht konfiguriert", "Drucken…", "Belegfußzeile", "Vielen Dank für Ihr Vertrauen.", "bereit", "verbunden", "verfügbar", "offline", "konfiguriert", "gedruckt", "fehlgeschlagen"],
  "zh-CN": ["打印机", "诊所服务器管理实体打印机。桌面端、网页端和移动端都通过此安全的本地连接打印。", "没有默认打印机", "在 Linux 上搜索，或输入 Windows 显示的蓝牙 COM 端口。", "打印测试页", "搜索打印机", "重新连接并测试", "未找到兼容的打印机。", "打印机搜索失败", "已保存默认打印机", "无法保存打印机", "测试页已打印", "测试打印失败", "默认打印机", "设为默认", "未检测到 RFCOMM 通道", "Windows 蓝牙 COM 端口", "在 Windows 设置中配对打印机，然后输入其传出 COM 端口。", "保存端口", "最近的打印尝试", "这里只保存技术记录，不保存医疗详情。", "打印机", "收据", "尚无打印尝试", "打印测试页或 POS 收据以验证连接。", "付款完成", "已成功保存。打印操作相互独立，可以安全重试。", "重新打印收据", "打印收据", "新销售", "热敏收据已打印", "付款已保存，但打印机不可用。", "打印机未配置", "正在打印…", "收据页脚", "感谢您的信任。", "就绪", "已连接", "可用", "离线", "已配置", "已打印", "失败"],
  ru: ["Принтеры", "Сервер клиники управляет физическим принтером. Компьютерные, веб- и мобильные клиенты печатают через это защищённое локальное соединение.", "Нет принтера по умолчанию", "Выполните поиск в Linux или введите Bluetooth COM-порт, показанный Windows.", "Печать тестовой страницы", "Поиск принтеров", "Переподключить и проверить", "Совместимый принтер не найден.", "Ошибка поиска принтеров", "Принтер по умолчанию сохранён", "Не удалось сохранить принтер", "Тестовая страница напечатана", "Ошибка тестовой печати", "Принтер по умолчанию", "Назначить по умолчанию", "Канал RFCOMM не обнаружен", "Bluetooth COM-порт Windows", "Сопрягите принтер в параметрах Windows, затем введите его исходящий COM-порт.", "Сохранить порт", "Недавние попытки печати", "Только техническая история; медицинские данные здесь не хранятся.", "Принтер", "Квитанция", "Попыток печати пока нет", "Напечатайте тестовую страницу или POS-квитанцию для проверки соединения.", "Платёж выполнен", "успешно сохранён. Печать независима, и её можно безопасно повторить.", "Повторно напечатать квитанцию", "Напечатать квитанцию", "Новая продажа", "Термоквитанция напечатана", "Платёж сохранён, но принтер недоступен.", "Принтер не настроен", "Печать…", "Нижний колонтитул квитанции", "Спасибо за ваше доверие.", "готов", "подключён", "доступен", "не в сети", "настроен", "напечатано", "ошибка"],
  ja: ["プリンター", "診療所サーバーが物理プリンターを管理します。デスクトップ、ウェブ、モバイルの各端末は、この安全なローカル接続を通じて印刷します。", "既定のプリンターがありません", "Linux で検索するか、Windows に表示される Bluetooth COM ポートを入力してください。", "テストページを印刷", "プリンターを検索", "再接続してテスト", "互換性のあるプリンターが見つかりません。", "プリンターの検索に失敗しました", "既定のプリンターを保存しました", "プリンターを保存できませんでした", "テストページを印刷しました", "テスト印刷に失敗しました", "既定のプリンター", "既定に設定", "RFCOMM チャンネルを検出できません", "Windows Bluetooth COM ポート", "Windows の設定でプリンターをペアリングし、送信 COM ポートを入力してください。", "ポートを保存", "最近の印刷履歴", "技術的な履歴のみで、医療情報は保存されません。", "プリンター", "領収書", "印刷履歴はまだありません", "接続を確認するため、テストページまたは POS 領収書を印刷してください。", "支払い完了", "正常に保存されました。印刷は独立しており、安全に再試行できます。", "領収書を再印刷", "領収書を印刷", "新しい販売", "感熱式領収書を印刷しました", "支払いは保存されましたが、プリンターを利用できません。", "プリンター未設定", "印刷中…", "領収書のフッター", "ご利用ありがとうございます。", "準備完了", "接続済み", "利用可能", "オフライン", "設定済み", "印刷済み", "失敗"],
  ko: ["프린터", "진료소 서버가 실제 프린터를 관리합니다. 데스크톱, 웹 및 모바일 클라이언트는 이 안전한 로컬 연결을 통해 인쇄합니다.", "기본 프린터 없음", "Linux에서 검색하거나 Windows에 표시된 Bluetooth COM 포트를 입력하세요.", "테스트 페이지 인쇄", "프린터 검색", "다시 연결하고 테스트", "호환되는 프린터를 찾지 못했습니다.", "프린터 검색 실패", "기본 프린터 저장됨", "프린터를 저장할 수 없습니다", "테스트 페이지 인쇄됨", "테스트 인쇄 실패", "기본 프린터", "기본값으로 설정", "RFCOMM 채널이 감지되지 않음", "Windows Bluetooth COM 포트", "Windows 설정에서 프린터를 페어링한 다음 송신 COM 포트를 입력하세요.", "포트 저장", "최근 인쇄 시도", "기술 기록만 저장되며 의료 정보는 저장되지 않습니다.", "프린터", "영수증", "아직 인쇄 시도가 없습니다", "연결을 확인하려면 테스트 페이지나 POS 영수증을 인쇄하세요.", "결제 완료", "성공적으로 저장되었습니다. 인쇄는 독립적이며 안전하게 다시 시도할 수 있습니다.", "영수증 재인쇄", "영수증 인쇄", "새 판매", "감열 영수증 인쇄됨", "결제는 저장되었지만 프린터를 사용할 수 없습니다.", "프린터가 구성되지 않음", "인쇄 중…", "영수증 바닥글", "신뢰해 주셔서 감사합니다.", "준비됨", "연결됨", "사용 가능", "오프라인", "구성됨", "인쇄됨", "실패"],
  id: ["Printer", "Server klinik mengelola printer fisik. Klien desktop, web, dan seluler mencetak melalui koneksi lokal aman ini.", "Tidak ada printer default", "Cari di Linux atau masukkan port COM Bluetooth yang ditampilkan Windows.", "Cetak halaman uji", "Cari printer", "Hubungkan kembali dan uji", "Tidak ditemukan printer yang kompatibel.", "Pencarian printer gagal", "Printer default disimpan", "Tidak dapat menyimpan printer", "Halaman uji dicetak", "Pencetakan uji gagal", "Printer default", "Jadikan default", "Kanal RFCOMM tidak terdeteksi", "Port COM Bluetooth Windows", "Pasangkan printer di Pengaturan Windows, lalu masukkan port COM keluar.", "Simpan port", "Upaya cetak terbaru", "Hanya riwayat teknis; tidak ada detail medis yang disimpan di sini.", "Printer", "Tanda terima", "Belum ada upaya cetak", "Cetak halaman uji atau tanda terima POS untuk memverifikasi koneksi.", "Pembayaran selesai", "berhasil disimpan. Pencetakan terpisah dan dapat dicoba lagi dengan aman.", "Cetak ulang tanda terima", "Cetak tanda terima", "Penjualan baru", "Tanda terima termal dicetak", "Pembayaran tersimpan, tetapi printer tidak tersedia.", "Printer belum dikonfigurasi", "Mencetak…", "Catatan kaki tanda terima", "Terima kasih atas kepercayaan Anda.", "siap", "terhubung", "tersedia", "offline", "dikonfigurasi", "dicetak", "gagal"],
};

export const printerTranslations = Object.fromEntries(Object.entries(values).map(([locale, messages]) => {
  if (messages.length !== keys.length) throw new Error(`Incomplete printer translations for ${locale}`);
  return [locale, Object.fromEntries(keys.map((key, index) => [key, messages[index]]))];
})) as Record<PrinterLocale, Record<(typeof keys)[number], string>>;

export const printerTranslationCatalog = keys;
