import { ShieldCheck } from "lucide-react";
import { api } from "../api";
import { useLoad } from "../hooks";
import { dateTime } from "../lib";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Badge, EmptyState, ErrorState, Skeleton, Table, Td, Th } from "../components/ui/data";
interface AuditItem{id:string;user:string;action:string;entityType:string;entityId:string;summary:string;ipAddress:string;createdAt:string}
export function AuditPage(){const audit=useLoad(()=>api.get<{items:AuditItem[]}>("/audit?limit=500"));return <div className="page"><div><p className="section-title">Security & attribution</p><h1 className="page-title">Audit log</h1><p className="page-description">Medical, financial, user and backup actions are attributable and timestamped.</p></div><Card className="mt-6"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-4 w-4"/>Recent security events</CardTitle><CardDescription>Audit history cannot be erased by nurse accounts.</CardDescription></CardHeader><CardContent>{audit.loading?<Skeleton className="h-80"/>:audit.error?<ErrorState message={audit.error.message} retry={audit.reload}/>:audit.data?.items.length?<Table><thead><tr><Th>Time</Th><Th>User</Th><Th>Action</Th><Th>Entity</Th><Th>Summary</Th><Th>IP / device</Th></tr></thead><tbody>{audit.data.items.map(item=><tr key={item.id}><Td className="whitespace-nowrap text-xs">{dateTime(item.createdAt)}</Td><Td className="font-semibold">{item.user}</Td><Td><Badge>{item.action.replaceAll("_"," ")}</Badge></Td><Td className="font-mono text-xs">{item.entityType}<br/><span className="text-zinc-400">{item.entityId.slice(0,8)}</span></Td><Td>{item.summary}</Td><Td className="max-w-44 truncate font-mono text-[10px] text-zinc-500">{item.ipAddress}</Td></tr>)}</tbody></Table>:<EmptyState title="No audit events" description="Important clinic actions will appear here."/>}</CardContent></Card></div>}

