import * as React from "react";
import { CheckCircle2, ClipboardPlus, Eye, FileSignature, Glasses, LockKeyhole, Save } from "lucide-react";
import { toast } from "sonner";
import { api, APIError } from "../api";
import { useAuth } from "../auth";
import { useLoad } from "../hooks";
import { dateTime } from "../lib";
import { useRealtime } from "../realtime";
import type { EncounterSummary, Patient } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "../components/ui/dialog";
import { Badge, EmptyState, ErrorState, Skeleton, Table, Td, Th } from "../components/ui/data";
import { Field, Input, Select, Textarea } from "../components/ui/input";
import { MacroTextarea } from "../components/macro-field";
import { EyeDiagramPanel } from "../components/eye-diagram";
import { CodeCombobox } from "../components/code-search";
import { SuperbillButton } from "../components/superbill";

interface Pretest {
  chiefComplaint: string; vitals: Record<string, string>; visualAcuity: Record<string, string>; autorefraction: Record<string, string>; keratometry: Record<string, string>; iop: Record<string, string>;
  pupils: string; eom: string; coverTest: string; confrontationFields: string; colorVision: string; stereopsis: string; pachymetry: Record<string, string>; lensometry: Record<string, string>; completedAt: string; version: number;
}
interface EncounterDetail extends EncounterSummary { appointmentId: string; hpi: string; treatmentPlan: string; followUp: string; pretest: Pretest; sections: Record<string, { data: Record<string, string>; version: number }>; diagnoses: { id: string; diagnosis: string; code: string; laterality: string; notes: string; primary: boolean }[]; addenda: { id: string; body: string; author: string; createdAt: string }[] }

export function ClinicalPage() {
  const { revision } = useRealtime(); const [createOpen, setCreateOpen] = React.useState(false); const [selectedID, setSelectedID] = React.useState<string | null>(null);
  const encounters = useLoad(() => api.get<{ items: EncounterSummary[] }>("/encounters"), [revision]);
  return <div className="page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-title">Ophthalmic chart</p><h1 className="page-title">Consultations</h1><p className="page-description">Independent pre-test and doctor sections prevent lost clinical work.</p></div><Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button><ClipboardPlus className="h-4 w-4" />Start consultation</Button></DialogTrigger><StartEncounter onSaved={(id) => { setCreateOpen(false); setSelectedID(id); encounters.reload(); }} /></Dialog></div>
    <Card className="mt-6 overflow-hidden">{encounters.loading ? <div className="p-5"><Skeleton className="h-72" /></div> : encounters.error ? <div className="p-5"><ErrorState message={encounters.error.message} retry={encounters.reload} /></div> : encounters.data?.items.length ? <><div className="hidden md:block"><Table><thead><tr><Th>Exam</Th><Th>Patient</Th><Th>Reason</Th><Th>Doctor</Th><Th>Status</Th><Th>Updated</Th></tr></thead><tbody>{encounters.data.items.map((item) => <tr key={item.id} className="cursor-pointer hover:bg-zinc-50" onClick={() => setSelectedID(item.id)}><Td className="font-mono text-xs font-bold">{item.encounterNumber}</Td><Td><strong>{item.patientName}</strong><div className="font-mono text-[11px] text-zinc-500">{item.medicalRecordNumber}</div></Td><Td>{item.chiefComplaint || item.visitReason || "—"}</Td><Td>{item.doctorName || "Unassigned"}</Td><Td><Badge tone={item.status === "finalized" ? "success" : "warning"}>{item.status}</Badge></Td><Td className="text-xs text-zinc-500">{dateTime(item.updatedAt)}</Td></tr>)}</tbody></Table></div><div className="divide-y md:hidden">{encounters.data.items.map((item) => <button key={item.id} onClick={() => setSelectedID(item.id)} className="w-full p-4 text-left"><div className="flex items-center justify-between"><span className="font-semibold">{item.patientName}</span><Badge tone={item.status === "finalized" ? "success" : "warning"}>{item.status}</Badge></div><div className="mt-1 font-mono text-xs text-zinc-500">{item.encounterNumber} · {dateTime(item.updatedAt)}</div></button>)}</div></> : <EmptyState title="No consultations yet" description="Start a consultation for a scheduled or walk-in patient." action={<Button onClick={() => setCreateOpen(true)}>Start consultation</Button>} />}</Card>
    <Dialog open={Boolean(selectedID)} onOpenChange={(open) => !open && setSelectedID(null)}>{selectedID && <EncounterWorkspace id={selectedID} onChanged={encounters.reload} />}</Dialog>
  </div>;
}

function StartEncounter({ onSaved }: { onSaved(id: string): void }) {
  const patients = useLoad(() => api.get<{ items: Patient[] }>("/patients?limit=100")); const [patientId, setPatientId] = React.useState(""); const [reason, setReason] = React.useState(""); const [complaint, setComplaint] = React.useState(""); const [saving, setSaving] = React.useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const result = await api.post<{ id: string }>("/encounters", { patientId, appointmentId: "", visitReason: reason, chiefComplaint: complaint, hpi: "", assessment: "", treatmentPlan: "", followUp: "" }); toast.success("Consultation started"); onSaved(result.id); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not start consultation"); } finally { setSaving(false); } };
  return <DialogContent><DialogHeader><DialogTitle>Start consultation</DialogTitle><DialogDescription>This creates a draft encounter and an independent nurse pre-test section.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={submit}><Field label="Patient"><Select required value={patientId} onChange={(event) => setPatientId(event.target.value)}><option value="">Select patient…</option>{patients.data?.items.map((patient) => <option key={patient.id} value={patient.id}>{patient.medicalRecordNumber} — {patient.firstName} {patient.lastName}</option>)}</Select></Field><Field label="Visit reason"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field><Field label="Chief complaint"><Textarea value={complaint} onChange={(event) => setComplaint(event.target.value)} /></Field><DialogFooter><Button type="submit" disabled={saving}>{saving ? "Starting…" : "Start consultation"}</Button></DialogFooter></form></DialogContent>;
}

function EncounterWorkspace({ id, onChanged }: { id: string; onChanged(): void }) {
  const { user } = useAuth(); const [tab, setTab] = React.useState<"pretest" | "exam" | "diagram" | "history">("pretest"); const detail = useLoad(() => api.get<EncounterDetail>(`/encounters/${id}`), [id]);
  if (detail.loading) return <DialogContent className="max-w-6xl"><Skeleton className="h-[70vh]" /></DialogContent>;
  if (detail.error || !detail.data) return <DialogContent><ErrorState message={detail.error?.message ?? "Encounter not found"} retry={detail.reload} /></DialogContent>;
  const encounter = detail.data; const locked = encounter.status === "finalized";
  return <DialogContent className="max-w-6xl p-0"><div className="border-b p-5 pr-12"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-mono text-xs font-bold text-zinc-500">{encounter.encounterNumber}</div><DialogTitle className="mt-1 text-xl">{encounter.patientName}</DialogTitle><DialogDescription>{encounter.chiefComplaint || encounter.visitReason || "Ophthalmic consultation"}</DialogDescription></div><Badge tone={locked ? "success" : "warning"}>{locked ? "Signed & locked" : "Draft"}</Badge></div><div className="mt-5 flex gap-1 overflow-x-auto"><Tab active={tab === "pretest"} onClick={() => setTab("pretest")}><Eye className="h-4 w-4" />Pre-test</Tab><Tab active={tab === "exam"} onClick={() => setTab("exam")}><FileSignature className="h-4 w-4" />Doctor exam</Tab><Tab active={tab === "diagram"} onClick={() => setTab("diagram")}><Glasses className="h-4 w-4" />Eye diagram</Tab><Tab active={tab === "history"} onClick={() => setTab("history")}><CheckCircle2 className="h-4 w-4" />Record history</Tab></div></div><div className="max-h-[75vh] overflow-y-auto p-5">{tab === "pretest" && <PretestEditor encounter={encounter} locked={locked} onSaved={() => { detail.reload(); onChanged(); }} />}{tab === "exam" && <DoctorExam encounter={encounter} canEdit={user?.role === "doctor" && !locked} onSaved={() => { detail.reload(); onChanged(); }} />}{tab === "diagram" && <EyeDiagramPanel encounterId={encounter.id} canEdit={user?.role === "doctor" && !locked} />}{tab === "history" && <div className="grid gap-5"><div className="flex justify-end"><SuperbillButton encounterId={encounter.id} /></div><Card><CardHeader><CardTitle>Diagnoses</CardTitle></CardHeader><CardContent>{encounter.diagnoses.length ? <div className="space-y-2">{encounter.diagnoses.map((diagnosis) => <div key={diagnosis.id} className="flex items-center gap-3 rounded-md border p-3"><Badge>{diagnosis.laterality || "OU"}</Badge><div className="flex-1"><strong>{diagnosis.diagnosis}</strong><div className="font-mono text-xs text-zinc-500">{diagnosis.code || "No code"}</div></div>{diagnosis.primary && <Badge tone="success">Primary</Badge>}</div>)}</div> : <EmptyState title="No diagnoses recorded" description="The doctor must add a diagnosis before finalizing." />}</CardContent></Card>{encounter.addenda.length > 0 && <Card><CardHeader><CardTitle>Signed addenda</CardTitle></CardHeader><CardContent className="space-y-3">{encounter.addenda.map((item) => <div key={item.id} className="border-l-2 border-black pl-4"><p className="text-sm">{item.body}</p><p className="mt-2 text-xs text-zinc-500">{item.author} · {dateTime(item.createdAt)}</p></div>)}</CardContent></Card>}</div>}</div></DialogContent>;
}

function Tab({ active, onClick, children }: { active: boolean; onClick(): void; children: React.ReactNode }) { return <button onClick={onClick} className={`flex min-h-10 items-center gap-2 whitespace-nowrap rounded-md px-3 text-sm font-semibold ${active ? "bg-black text-white" : "text-zinc-500 hover:bg-zinc-100"}`}>{children}</button>; }

const emptyEye = { distance: "", near: "", sphere: "", cylinder: "", axis: "" };
function PretestEditor({ encounter, locked, onSaved }: { encounter: EncounterDetail; locked: boolean; onSaved(): void }) {
  const source = encounter.pretest;
  const [complaint, setComplaint] = React.useState(source?.chiefComplaint ?? encounter.chiefComplaint);
  const [vitals, setVitals] = React.useState<Record<string, string>>(source?.vitals ?? {});
  const [va, setVA] = React.useState<Record<string, string>>(source?.visualAcuity ?? {});
  const [auto, setAuto] = React.useState<Record<string, string>>(source?.autorefraction ?? {});
  const [keratometry, setKeratometry] = React.useState<Record<string, string>>(source?.keratometry ?? {});
  const [iop, setIOP] = React.useState<Record<string, string>>(source?.iop ?? {});
  const [pachymetry, setPachymetry] = React.useState<Record<string, string>>(source?.pachymetry ?? {});
  const [lensometry, setLensometry] = React.useState<Record<string, string>>(source?.lensometry ?? {});
  const [screening, setScreening] = React.useState({ pupils: source?.pupils ?? "", eom: source?.eom ?? "", coverTest: source?.coverTest ?? "", confrontationFields: source?.confrontationFields ?? "", colorVision: source?.colorVision ?? "", stereopsis: source?.stereopsis ?? "" });
  const [saving, setSaving] = React.useState(false); const [conflict, setConflict] = React.useState(false);
  const save = async (complete: boolean) => { setSaving(true); setConflict(false); try { await api.put(`/encounters/${encounter.id}/pretest`, { chiefComplaint: complaint, vitals, visualAcuity: va, autorefraction: auto, keratometry, iop, ...screening, pachymetry, lensometry, complete, version: source?.version ?? 1 }); toast.success(complete ? "Pre-test completed" : "Pre-test saved"); onSaved(); } catch (reason) { if (reason instanceof APIError && reason.isConflict) setConflict(true); else toast.error(reason instanceof Error ? reason.message : "Could not save pre-test"); } finally { setSaving(false); } };
  return <div className="grid gap-5"><Card><CardHeader><CardTitle>Nurse pre-test</CardTitle><CardDescription>This section has its own version, separate from the doctor's consultation notes.</CardDescription></CardHeader><CardContent className="grid gap-6"><Field label="Chief complaint"><Textarea disabled={locked} value={complaint} onChange={(event) => setComplaint(event.target.value)} /></Field>
    <section><h3 className="mb-3 text-sm font-bold">Vitals</h3><div className="grid gap-3 sm:grid-cols-4"><CompactField label="Blood pressure" field="bloodPressure" values={vitals} onChange={setVitals} disabled={locked} /><CompactField label="Pulse" field="pulse" values={vitals} onChange={setVitals} disabled={locked} /><CompactField label="Temperature" field="temperature" values={vitals} onChange={setVitals} disabled={locked} /><CompactField label="Blood glucose" field="bloodGlucose" values={vitals} onChange={setVitals} disabled={locked} /></div></section>
    <EyeGrid title="Visual acuity" fields={["Uncorrected distance", "Uncorrected near", "Presenting distance", "Presenting near", "Corrected distance", "Best corrected VA", "Pinhole"]} values={va} onChange={setVA} disabled={locked} />
    <EyeGrid title="Autorefraction" fields={["Sphere", "Cylinder", "Axis"]} values={auto} onChange={setAuto} disabled={locked} />
    <EyeGrid title="Keratometry" fields={["K1", "K1 Axis", "K2", "K2 Axis"]} values={keratometry} onChange={setKeratometry} disabled={locked} />
    <EyeGrid title="Intraocular pressure" fields={["IOP", "Method", "Time"]} values={iop} onChange={setIOP} disabled={locked} />
    <section><h3 className="mb-3 text-sm font-bold">Preliminary screening</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{([['Pupils','pupils'],['EOM','eom'],['Cover test','coverTest'],['Confrontation fields','confrontationFields'],['Color vision','colorVision'],['Stereopsis','stereopsis']] as const).map(([label, field]) => <Field key={field} label={label}><Input disabled={locked} value={screening[field]} onChange={(event) => setScreening({ ...screening, [field]: event.target.value })} /></Field>)}</div></section>
    <EyeGrid title="Pachymetry" fields={["Thickness"]} values={pachymetry} onChange={setPachymetry} disabled={locked} />
    <EyeGrid title="Lensometry / current correction" fields={["Sphere", "Cylinder", "Axis", "Add", "Prism", "Base"]} values={lensometry} onChange={setLensometry} disabled={locked} />
    {conflict && <Conflict />}{!locked && <div className="sticky bottom-0 flex flex-col gap-2 border-t bg-white py-3 sm:flex-row sm:justify-end"><Button variant="outline" disabled={saving} onClick={() => save(false)}><Save className="h-4 w-4" />Save draft</Button><Button disabled={saving} onClick={() => save(true)}><CheckCircle2 className="h-4 w-4" />Complete pre-test</Button></div>}</CardContent></Card></div>;
}

function DoctorExam({ encounter, canEdit, onSaved }: { encounter: EncounterDetail; canEdit: boolean; onSaved(): void }) {
  const { user } = useAuth();
  const section = (name: string) => encounter.sections[name];
  const [form, setForm] = React.useState({ visitReason: encounter.visitReason, chiefComplaint: encounter.chiefComplaint, hpi: encounter.hpi, assessment: encounter.assessment, treatmentPlan: encounter.treatmentPlan, followUp: encounter.followUp });
  const [currentCorrection, setCurrentCorrection] = React.useState<Record<string, string>>(section("current_correction")?.data ?? {});
  const [objective, setObjective] = React.useState<Record<string, string>>(section("objective_refraction")?.data ?? {});
  const [rx, setRx] = React.useState<Record<string, string>>(section("subjective_refraction")?.data ?? {});
  const [cycloplegic, setCycloplegic] = React.useState<Record<string, string>>(section("cycloplegic_refraction")?.data ?? {});
  const [anterior, setAnterior] = React.useState<Record<string, string>>(section("anterior_segment")?.data ?? {});
  const [posterior, setPosterior] = React.useState<Record<string, string>>(section("posterior_segment")?.data ?? {});
  const [otherExam, setOtherExam] = React.useState<Record<string, string>>(section("other_exam")?.data ?? {});
  const [diagnosis, setDiagnosis] = React.useState({ diagnosis: "", code: "", laterality: "OU", notes: "", primary: true }); const [saving, setSaving] = React.useState(false); const [conflict, setConflict] = React.useState(false);
  const saveCore = async () => { setSaving(true); setConflict(false); try { await api.put(`/encounters/${encounter.id}`, { ...form, patientId: encounter.patientId, appointmentId: encounter.appointmentId, version: encounter.version }); toast.success("Assessment and plan saved"); onSaved(); } catch (reason) { if (reason instanceof APIError && reason.isConflict) setConflict(true); else toast.error(reason instanceof Error ? reason.message : "Could not save assessment"); } finally { setSaving(false); } };
  const saveSection = async (name: string, data: Record<string, string>) => { setSaving(true); setConflict(false); try { await api.put(`/encounters/${encounter.id}/sections/${name}`, { data, version: section(name)?.version ?? 0 }); toast.success("Clinical section saved"); onSaved(); } catch (reason) { if (reason instanceof APIError && reason.isConflict) setConflict(true); else toast.error(reason instanceof Error ? reason.message : "Could not save clinical section"); } finally { setSaving(false); } };
  const addDiagnosis = async () => { try { await api.post(`/encounters/${encounter.id}/diagnoses`, diagnosis); toast.success("Diagnosis added"); setDiagnosis({ diagnosis: "", code: "", laterality: "OU", notes: "", primary: false }); onSaved(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not add diagnosis"); } };
  const finalize = async () => { if (!confirm("Sign and finalize this consultation? Normal editing will be permanently locked.")) return; try { await api.post(`/encounters/${encounter.id}/finalize`, { version: encounter.version }); toast.success("Consultation signed and locked"); onSaved(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not finalize"); } };
  if (user?.role !== "doctor") return <EmptyState title="Doctor access required" description="Nurses may view finalized findings but cannot enter diagnoses, prescribe, or sign consultations." />;
  return <div className="grid gap-5"><Card><CardHeader><CardTitle>Clinical history</CardTitle><CardDescription>{canEdit ? "Draft findings are versioned and auditable." : "This signed consultation is read-only."}</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Visit reason"><Input disabled={!canEdit} value={form.visitReason} onChange={(event) => setForm({ ...form, visitReason: event.target.value })} /></Field><Field label="Chief complaint"><Input disabled={!canEdit} value={form.chiefComplaint} onChange={(event) => setForm({ ...form, chiefComplaint: event.target.value })} /></Field></div>{canEdit ? <MacroTextarea label="History of present illness" category="hpi" value={form.hpi} onChange={(value) => setForm({ ...form, hpi: value })} /> : <Field label="History of present illness"><Textarea disabled value={form.hpi} /></Field>}</CardContent></Card>
    <ClinicalSection title="Current correction / lensometry" description="Existing spectacle or contact-lens correction." sectionName="current_correction" values={currentCorrection} onChange={setCurrentCorrection} fields={["Sphere", "Cylinder", "Axis", "Add", "Prism", "Base"]} canEdit={canEdit} saving={saving} onSave={saveSection} />
    <ClinicalSection title="Objective refraction / retinoscopy" description="Objective and retinoscopy measurements." sectionName="objective_refraction" values={objective} onChange={setObjective} fields={["Sphere", "Cylinder", "Axis", "Working distance"]} canEdit={canEdit} saving={saving} onSave={saveSection} />
    <ClinicalSection title="Subjective refraction" description="Final subjective refraction and PD." sectionName="subjective_refraction" values={rx} onChange={setRx} fields={["Sphere", "Cylinder", "Axis", "Add", "Prism", "Base"]} canEdit={canEdit} saving={saving} onSave={saveSection} extra={<div className="grid gap-3 sm:grid-cols-3"><CompactField label="Binocular PD" field="pd" values={rx} onChange={setRx} disabled={!canEdit} /><CompactField label="Monocular PD OD" field="pdOD" values={rx} onChange={setRx} disabled={!canEdit} /><CompactField label="Monocular PD OS" field="pdOS" values={rx} onChange={setRx} disabled={!canEdit} /></div>} />
    <ClinicalSection title="Cycloplegic refraction" description="Optional cycloplegic findings." sectionName="cycloplegic_refraction" values={cycloplegic} onChange={setCycloplegic} fields={["Sphere", "Cylinder", "Axis"]} canEdit={canEdit} saving={saving} onSave={saveSection} />
    <ClinicalSection title="Anterior segment / slit lamp" description="Use Normal when appropriate or enter specific findings." sectionName="anterior_segment" values={anterior} onChange={setAnterior} fields={["Lids / lashes", "Conjunctiva", "Cornea", "Anterior chamber", "Iris", "Lens"]} canEdit={canEdit} saving={saving} onSave={saveSection} />
    <ClinicalSection title="Posterior segment / fundus" description="Record each eye independently." sectionName="posterior_segment" values={posterior} onChange={setPosterior} fields={["Optic nerve", "Cup / disc ratio", "Macula", "Vessels", "Retina", "Peripheral retina"]} canEdit={canEdit} saving={saving} onSave={saveSection} />
    <Card><CardHeader><CardTitle>Other examination findings</CardTitle><CardDescription>Optional binocular and specialty observations.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Pupils", "EOM", "Cover test", "Visual fields", "Color vision", "Stereopsis"].map((field) => <CompactField key={field} label={field} field={field.replaceAll(" ", "").toLowerCase()} values={otherExam} onChange={setOtherExam} disabled={!canEdit} />)}</div>{canEdit && <div className="flex justify-end"><Button variant="outline" disabled={saving} onClick={() => saveSection("other_exam", otherExam)}><Save className="h-4 w-4" />Save findings</Button></div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Assessment & plan</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2">{canEdit ? <MacroTextarea label="Assessment" category="assessment" value={form.assessment} onChange={(value) => setForm({ ...form, assessment: value })} /> : <Field label="Assessment"><Textarea disabled value={form.assessment} /></Field>}{canEdit ? <MacroTextarea label="Treatment plan" category="treatment_plan" value={form.treatmentPlan} onChange={(value) => setForm({ ...form, treatmentPlan: value })} /> : <Field label="Treatment plan"><Textarea disabled value={form.treatmentPlan} /></Field>}</div><Field label="Follow-up"><Input disabled={!canEdit} value={form.followUp} onChange={(event) => setForm({ ...form, followUp: event.target.value })} /></Field>{conflict && <Conflict />}{canEdit && <div className="flex justify-end"><Button disabled={saving} onClick={saveCore}><Save className="h-4 w-4" />Save assessment</Button></div>}</CardContent></Card>
    {canEdit && <Card><CardHeader><CardTitle>Diagnosis</CardTitle><CardDescription>Search ICD-10 to fill the fields, or type your own — coding assist works fully offline.</CardDescription></CardHeader><CardContent className="grid gap-4"><Field label="Search ICD-10"><CodeCombobox endpoint="/codes/icd10" placeholder="Search by code or description…" onSelect={(entry) => setDiagnosis({ ...diagnosis, diagnosis: entry.description, code: entry.code })} /></Field><div className="grid gap-4 sm:grid-cols-[1fr_160px_120px]"><Field label="Diagnosis"><Input value={diagnosis.diagnosis} onChange={(event) => setDiagnosis({ ...diagnosis, diagnosis: event.target.value })} /></Field><Field label="ICD-10 code"><Input className="font-mono" value={diagnosis.code} onChange={(event) => setDiagnosis({ ...diagnosis, code: event.target.value })} /></Field><Field label="Eye"><Select value={diagnosis.laterality} onChange={(event) => setDiagnosis({ ...diagnosis, laterality: event.target.value })}><option>OU</option><option>OD</option><option>OS</option></Select></Field></div><div className="flex justify-end"><Button variant="outline" disabled={!diagnosis.diagnosis} onClick={addDiagnosis}>Add diagnosis</Button></div></CardContent></Card>}
    {canEdit && <PrescriptionComposer encounter={encounter} subjective={rx} treatmentPlan={form.treatmentPlan} />}
    {canEdit && <Card className="border-black"><CardHeader><CardTitle>Finalize medical record</CardTitle><CardDescription>Signing locks the consultation. Future corrections must be appended as addenda.</CardDescription></CardHeader><CardContent className="flex justify-end"><Button disabled={encounter.diagnoses.length === 0} onClick={finalize}><LockKeyhole className="h-4 w-4" />Sign & finalize</Button></CardContent></Card>}
  </div>;
}

function ClinicalSection({ title, description, sectionName, values, onChange, fields, canEdit, saving, onSave, extra }: { title: string; description: string; sectionName: string; values: Record<string, string>; onChange(value: Record<string, string>): void; fields: string[]; canEdit: boolean; saving: boolean; onSave(name: string, data: Record<string, string>): void; extra?: React.ReactNode }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="grid gap-4"><EyeGrid title="OD / OS" fields={fields} values={values} onChange={onChange} disabled={!canEdit} />{extra}{canEdit && <div className="flex justify-end"><Button variant="outline" disabled={saving} onClick={() => onSave(sectionName, values)}><Save className="h-4 w-4" />Save section</Button></div>}</CardContent></Card>;
}

function PrescriptionComposer({ encounter, subjective, treatmentPlan }: { encounter: EncounterDetail; subjective: Record<string, string>; treatmentPlan: string }) {
  const [type, setType] = React.useState<"spectacle" | "contact_lens" | "medication">("spectacle"); const [contact, setContact] = React.useState<Record<string, string>>({}); const [medication, setMedication] = React.useState({ medication: "", strength: "", dosage: "", frequency: "", route: "ophthalmic", duration: "", instructions: "" }); const [expiresAt, setExpiresAt] = React.useState(""); const [notes, setNotes] = React.useState(treatmentPlan); const [saving, setSaving] = React.useState(false);
  const issue = async () => { setSaving(true); try { const od = type === "spectacle" ? Object.fromEntries(Object.entries(subjective).filter(([key]) => key.startsWith("od"))) : type === "contact_lens" ? Object.fromEntries(Object.entries(contact).filter(([key]) => key.startsWith("od"))) : {}; const os = type === "spectacle" ? Object.fromEntries(Object.entries(subjective).filter(([key]) => key.startsWith("os"))) : type === "contact_lens" ? Object.fromEntries(Object.entries(contact).filter(([key]) => key.startsWith("os"))) : {}; const details = type === "spectacle" ? { pd: subjective.pd ?? "", pdOD: subjective.pdOD ?? "", pdOS: subjective.pdOS ?? "" } : type === "contact_lens" ? { manufacturer: contact.manufacturer ?? "", brand: contact.brand ?? "", material: contact.material ?? "", replacementSchedule: contact.replacementSchedule ?? "" } : medication; await api.post("/prescriptions", { patientId: encounter.patientId, encounterId: encounter.id, type, od, os, details, notes, expiresAt }); toast.success(`${type.replaceAll("_", " ")} prescription issued`); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not issue prescription"); } finally { setSaving(false); } };
  const valid = type === "spectacle" ? Object.keys(subjective).some((key) => key.startsWith("od") || key.startsWith("os")) : type === "contact_lens" ? Object.keys(contact).some((key) => key.startsWith("od") || key.startsWith("os")) : medication.medication.trim() !== "" && medication.dosage.trim() !== "";
  return <Card className="border-black"><CardHeader><CardTitle>Issue prescription</CardTitle><CardDescription>Spectacle, contact-lens and medication prescriptions are doctor-only final records.</CardDescription></CardHeader><CardContent className="grid gap-4"><Field label="Prescription type"><Select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="spectacle">Spectacle</option><option value="contact_lens">Contact lens</option><option value="medication">Medication</option></Select></Field>{type === "spectacle" && <div className="rounded-md bg-zinc-50 p-3 text-sm">The current subjective refraction and PD values will be copied into the prescription.</div>}{type === "contact_lens" && <><EyeGrid title="Contact lens parameters" fields={["Power", "BC", "DIA", "Cylinder", "Axis", "Add"]} values={contact} onChange={setContact} disabled={false} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CompactField label="Manufacturer" field="manufacturer" values={contact} onChange={setContact} disabled={false} /><CompactField label="Brand" field="brand" values={contact} onChange={setContact} disabled={false} /><CompactField label="Material" field="material" values={contact} onChange={setContact} disabled={false} /><CompactField label="Replacement" field="replacementSchedule" values={contact} onChange={setContact} disabled={false} /></div></>}{type === "medication" && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{([['Medication','medication'],['Strength','strength'],['Dosage','dosage'],['Frequency','frequency'],['Route','route'],['Duration','duration']] as const).map(([label, field]) => <Field key={field} label={label}><Input required={field === "medication" || field === "dosage"} value={medication[field]} onChange={(event) => setMedication({ ...medication, [field]: event.target.value })} /></Field>)}<Field label="Instructions"><Textarea className="sm:col-span-2 lg:col-span-3" value={medication.instructions} onChange={(event) => setMedication({ ...medication, instructions: event.target.value })} /></Field></div>}<div className="grid gap-3 sm:grid-cols-2"><Field label="Expiration date"><Input type="date" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></Field><Field label="Notes"><Input value={notes} onChange={(event) => setNotes(event.target.value)} /></Field></div><div className="flex justify-end"><Button disabled={!valid || saving} onClick={issue}><Glasses className="h-4 w-4" />{saving ? "Issuing…" : "Issue prescription"}</Button></div></CardContent></Card>;
}

function CompactField({ label, field, values, onChange, disabled }: { label: string; field: string; values: Record<string, string>; onChange(value: Record<string, string>): void; disabled: boolean }) { return <Field label={label}><Input disabled={disabled} value={values[field] ?? ""} onChange={(event) => onChange({ ...values, [field]: event.target.value })} /></Field>; }

function EyeGrid({ title, fields, values, onChange, disabled }: { title: string; fields: string[]; values: Record<string, string>; onChange(value: Record<string, string>): void; disabled: boolean }) { const key = (eye: string, field: string) => `${eye}${field.replaceAll(" ", "")}`.toLowerCase(); return <div><div className="mb-2 text-sm font-bold">{title}</div><div className="grid grid-cols-[minmax(90px,1fr)_1fr_1fr] overflow-hidden rounded-lg border"><div className="bg-zinc-50 p-3" /><div className="bg-zinc-50 p-3 text-center font-mono text-xs font-bold">OD</div><div className="bg-zinc-50 p-3 text-center font-mono text-xs font-bold">OS</div>{fields.map((field) => <React.Fragment key={field}><div className="border-t bg-zinc-50 p-3 text-xs font-semibold text-zinc-600">{field}</div>{["od", "os"].map((eye) => <div className="border-l border-t p-1.5" key={eye}><Input className="h-9 min-w-0 border-0 font-mono text-center focus-visible:ring-1" disabled={disabled} value={values[key(eye, field)] ?? emptyEye.distance.slice(0,0)} onChange={(event) => onChange({ ...values, [key(eye, field)]: event.target.value })} /></div>)}</React.Fragment>)}</div></div>; }
function Conflict() { return <div role="alert" className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>This record changed on another device.</strong><p>Reload and review the latest values before saving again.</p></div>; }
