import * as React from "react";
import { FileUp, Plus, Search, UserRound, X } from "lucide-react";
import { toast } from "sonner";
import { api, APIError } from "../api";
import { useLoad } from "../hooks";
import { dateTime } from "../lib";
import { useRealtime } from "../realtime";
import type { Patient } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "../components/ui/dialog";
import { Badge, EmptyState, ErrorState, Skeleton, Table, Td, Th } from "../components/ui/data";
import { Field, Input, Select, Textarea } from "../components/ui/input";

const emptyPatient = { firstName: "", middleName: "", lastName: "", preferredName: "", sex: "", dateOfBirth: "", phone: "", alternatePhone: "", email: "", address: "", city: "", occupation: "", employer: "", preferredLanguage: "", communicationPreference: "", referralSource: "", referringProvider: "", notes: "", tags: [] as string[] };
export function PatientsPage() {
  const { revision } = useRealtime(); const [query, setQuery] = React.useState(""); const [debounced, setDebounced] = React.useState(""); const [createOpen, setCreateOpen] = React.useState(false); const [selected, setSelected] = React.useState<Patient | null>(null);
  React.useEffect(() => { const timer = setTimeout(() => setDebounced(query), 200); return () => clearTimeout(timer); }, [query]);
  const patients = useLoad(() => api.get<{ items: Patient[]; total: number }>(`/patients?q=${encodeURIComponent(debounced)}`), [debounced, revision]);
  React.useEffect(() => { const id = new URLSearchParams(location.search).get("id"); if (id) api.get<Patient>(`/patients/${id}`).then(setSelected).catch(() => undefined); }, []);
  return <div className="page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-title">Patient records</p><h1 className="page-title">Patients</h1><p className="page-description">Demographics, history, clinical timeline, financial and optical records.</p></div><Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button><Plus className="h-4 w-4" />New patient</Button></DialogTrigger><PatientForm onSaved={(patient) => { setCreateOpen(false); setSelected(patient); patients.reload(); }} /></Dialog></div>
    <div className="relative mt-6 max-w-xl"><Search className="absolute left-3 top-3.5 h-4 w-4 text-zinc-400" /><Input className="pl-10" placeholder="Name, medical record number, phone, email…" value={query} onChange={(event) => setQuery(event.target.value)} /></div>
    <Card className="mt-4 overflow-hidden">{patients.loading ? <div className="p-5"><Skeleton className="h-72" /></div> : patients.error ? <div className="p-5"><ErrorState message={patients.error.message} retry={patients.reload} /></div> : !patients.data?.items.length ? <EmptyState title="No patients found" description={query ? "Try another search." : "Create the first patient to begin the clinic workflow."} action={!query && <Button onClick={() => setCreateOpen(true)}>Create patient</Button>} /> : <><div className="hidden md:block"><Table><thead><tr><Th>Patient no.</Th><Th>Name</Th><Th>Demographics</Th><Th>Phone</Th><Th>Tags</Th><Th>Updated</Th></tr></thead><tbody>{patients.data.items.map((patient) => <tr key={patient.id} className="cursor-pointer hover:bg-zinc-50" onClick={() => setSelected(patient)}><Td className="font-mono text-xs font-bold">{patient.medicalRecordNumber}</Td><Td><div className="font-semibold">{patient.firstName} {patient.lastName}</div><div className="text-xs text-zinc-500">{patient.email || "No email"}</div></Td><Td>{patient.dateOfBirth || "—"} · {patient.sex || "—"}</Td><Td>{patient.phone || "—"}</Td><Td><div className="flex flex-wrap gap-1">{patient.tags.map((tag) => <Badge key={tag}>{tag}</Badge>)}</div></Td><Td className="text-xs text-zinc-500">{dateTime(patient.updatedAt)}</Td></tr>)}</tbody></Table></div><div className="divide-y md:hidden">{patients.data.items.map((patient) => <button key={patient.id} onClick={() => setSelected(patient)} className="flex w-full items-center gap-3 p-4 text-left"><div className="grid h-10 w-10 place-items-center rounded-full bg-zinc-100"><UserRound className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="font-semibold">{patient.firstName} {patient.lastName}</div><div className="font-mono text-xs text-zinc-500">{patient.medicalRecordNumber} · {patient.phone || "No phone"}</div></div></button>)}</div></>}</Card>
    {selected && <PatientPanel patient={selected} onClose={() => setSelected(null)} onChanged={(patient) => { setSelected(patient); patients.reload(); }} />}
  </div>;
}

function PatientForm({ patient, onSaved }: { patient?: Patient; onSaved(patient: Patient): void }) {
  const [form, setForm] = React.useState(patient ? { ...emptyPatient, ...patient } : emptyPatient); const [saving, setSaving] = React.useState(false); const [conflict, setConflict] = React.useState(false);
  const update = (key: keyof typeof emptyPatient) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setConflict(false); try { const result = patient ? await api.put<Patient>(`/patients/${patient.id}`, { ...form, version: patient.version }) : await api.post<Patient>("/patients", form); toast.success(patient ? "Patient updated" : "Patient created"); onSaved(result); } catch (reason) { if (reason instanceof APIError && reason.isConflict) setConflict(true); else toast.error(reason instanceof Error ? reason.message : "Could not save patient"); } finally { setSaving(false); } };
  return <DialogContent><DialogHeader><DialogTitle>{patient ? "Edit patient record" : "Register a new patient"}</DialogTitle><DialogDescription>Only identity is required now. Optional clinical and contact data can be completed later.</DialogDescription></DialogHeader><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="First name"><Input required value={form.firstName} onChange={update("firstName")} /></Field><Field label="Last name"><Input required value={form.lastName} onChange={update("lastName")} /></Field><Field label="Middle name"><Input value={form.middleName} onChange={update("middleName")} /></Field><Field label="Preferred name"><Input value={form.preferredName} onChange={update("preferredName")} /></Field><Field label="Date of birth"><Input type="date" value={form.dateOfBirth} onChange={update("dateOfBirth")} /></Field><Field label="Sex"><Select value={form.sex} onChange={update("sex")}><option value="">Not specified</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></Select></Field><Field label="Phone"><Input value={form.phone} onChange={update("phone")} /></Field><Field label="Alternate phone"><Input value={form.alternatePhone} onChange={update("alternatePhone")} /></Field><Field label="Email"><Input type="email" value={form.email} onChange={update("email")} /></Field><Field label="City / area"><Input value={form.city} onChange={update("city")} /></Field><Field label="Address"><Input value={form.address} onChange={update("address")} /></Field><Field label="Occupation"><Input value={form.occupation} onChange={update("occupation")} /></Field><div className="sm:col-span-2"><Field label="Notes"><Textarea value={form.notes} onChange={update("notes")} /></Field></div></div>{conflict && <div role="alert" className="mt-4 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>This record was modified by another user.</strong><p>Close and reload the latest patient record before saving.</p></div>}<DialogFooter><Button type="submit" disabled={saving}>{saving ? "Saving…" : patient ? "Save changes" : "Create patient"}</Button></DialogFooter></form></DialogContent>;
}

function PatientPanel({ patient, onClose, onChanged }: { patient: Patient; onClose(): void; onChanged(patient: Patient): void }) {
  const [editing, setEditing] = React.useState(false); const timeline = useLoad(() => api.get<{ items: { type: string; id: string; at: string; title: string }[] }>(`/patients/${patient.id}/timeline`), [patient.id]); const [uploading, setUploading] = React.useState(false);
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); const body = new FormData(); body.set("patientId", patient.id); body.set("category", "patient_document"); body.set("file", file); try { await api.post("/documents", body); toast.success("Document uploaded"); timeline.reload(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Upload failed"); } finally { setUploading(false); } };
  return <div className="fixed inset-0 z-40"><button aria-label="Close patient" className="absolute inset-0 bg-black/30" onClick={onClose} /><aside className="absolute inset-y-0 right-0 w-full max-w-2xl overflow-y-auto bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center gap-3 border-b bg-white p-4 pt-[max(1rem,env(safe-area-inset-top))]"><div className="min-w-0 flex-1"><div className="font-mono text-xs font-bold text-zinc-500">{patient.medicalRecordNumber}</div><h2 className="truncate text-xl font-bold">{patient.firstName} {patient.lastName}</h2></div><Button variant="outline" onClick={() => setEditing(true)}>Edit</Button><Button size="icon" variant="ghost" onClick={onClose}><X className="h-5 w-5" /></Button></div><div className="grid gap-4 p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:p-6"><Card><CardHeader><CardTitle>Patient overview</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-2"><Info label="Date of birth" value={patient.dateOfBirth} /><Info label="Phone" value={patient.phone} /><Info label="Email" value={patient.email} /><Info label="City" value={patient.city} /><Info label="Address" value={patient.address} /><Info label="Language" value={patient.preferredLanguage} /></CardContent></Card><MedicalHistory patientId={patient.id} /><Card><CardHeader><CardTitle>Documents</CardTitle></CardHeader><CardContent><label className="flex min-h-16 cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-zinc-300 p-5 text-sm font-semibold hover:bg-zinc-50"><FileUp className="h-4 w-4" />{uploading ? "Uploading…" : "Upload PDF, image or document"}<input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={upload} disabled={uploading} /></label></CardContent></Card><Card><CardHeader><CardTitle>Longitudinal timeline</CardTitle></CardHeader><CardContent>{timeline.loading ? <Skeleton className="h-48" /> : timeline.data?.items.length ? <div className="relative ml-2 border-l border-zinc-200 pl-5">{timeline.data.items.map((item) => <div key={`${item.type}-${item.id}`} className="relative pb-5"><span className="absolute -left-[25px] top-1 h-2 w-2 rounded-full bg-black" /><div className="text-sm font-semibold">{item.title}</div><div className="mt-1 text-xs text-zinc-500">{dateTime(item.at)}</div></div>)}</div> : <EmptyState title="No patient activity yet" description="Appointments, consultations, prescriptions, payments and lab orders appear here." />}</CardContent></Card></div></aside><Dialog open={editing} onOpenChange={setEditing}>{editing && <PatientForm patient={patient} onSaved={(updated) => { setEditing(false); onChanged(updated); }} />}</Dialog></div>;
}
function Info({ label, value }: { label: string; value?: string }) { return <div><div className="text-xs font-semibold text-zinc-500">{label}</div><div className="mt-1">{value || "—"}</div></div>; }

interface HistoryRecord {
  chronicDiseases: string[]; diabetes: boolean | null; hypertension: boolean | null; cardiovascularNotes: string; neurologicalNotes: string; surgeries: string; pregnancyNotes: string; tobaccoUse: string; familyMedicalHistory: string; familyOcularHistory: string; previousEyeSurgery: string; ocularTrauma: string; glaucomaHistory: string; cataractHistory: string; retinalDisease: string; previousGlasses: string; previousContactLenses: string; version: number; updatedAt: string;
}

function MedicalHistory({ patientId }: { patientId: string }) {
  const history = useLoad(() => api.get<HistoryRecord>(`/patients/${patientId}/history`), [patientId]);
  const [editing, setEditing] = React.useState(false);
  if (history.loading) return <Card><CardContent className="p-5"><Skeleton className="h-28" /></CardContent></Card>;
  if (history.error || !history.data) return <Card><CardContent className="p-5"><ErrorState message={history.error?.message ?? "Medical history unavailable"} retry={history.reload} /></CardContent></Card>;
  const item = history.data;
  const highlights = [item.diabetes === true && "Diabetes", item.hypertension === true && "Hypertension", item.glaucomaHistory && "Glaucoma history", item.cataractHistory && "Cataract history", ...item.chronicDiseases].filter(Boolean) as string[];
  return <><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Medical & ocular history</CardTitle><p className="mt-1 text-xs text-zinc-500">Structured intake, independently versioned</p></div><Button size="sm" variant="outline" onClick={() => setEditing(true)}>Review</Button></CardHeader><CardContent>{highlights.length ? <div className="flex flex-wrap gap-2">{highlights.map((value) => <Badge key={value} tone="warning">{value}</Badge>)}</div> : <p className="text-sm text-zinc-500">No significant history recorded.</p>}</CardContent></Card><Dialog open={editing} onOpenChange={setEditing}><HistoryForm history={item} patientId={patientId} onSaved={() => { setEditing(false); history.reload(); }} /></Dialog></>;
}

function HistoryForm({ history, patientId, onSaved }: { history: HistoryRecord; patientId: string; onSaved(): void }) {
  const [form, setForm] = React.useState(history);
  const [chronic, setChronic] = React.useState(history.chronicDiseases.join(", "));
  const [saving, setSaving] = React.useState(false);
  const [conflict, setConflict] = React.useState(false);
  const update = (key: keyof HistoryRecord) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [key]: event.target.value });
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setConflict(false); try { await api.put(`/patients/${patientId}/history`, { ...form, chronicDiseases: chronic.split(",").map((value) => value.trim()).filter(Boolean) }); toast.success("Medical history updated"); onSaved(); } catch (reason) { if (reason instanceof APIError && reason.isConflict) setConflict(true); else toast.error(reason instanceof Error ? reason.message : "Could not update medical history"); } finally { setSaving(false); } };
  return <DialogContent><DialogHeader><DialogTitle>Medical & ocular history</DialogTitle><DialogDescription>Fields are optional. Unknown remains distinct from No.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><TriState label="Diabetes" value={form.diabetes} onChange={(diabetes) => setForm({ ...form, diabetes })} /><TriState label="Hypertension" value={form.hypertension} onChange={(hypertension) => setForm({ ...form, hypertension })} /></div><Field label="Chronic diseases" hint="Separate multiple conditions with commas"><Input value={chronic} onChange={(event) => setChronic(event.target.value)} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Cardiovascular history"><Textarea value={form.cardiovascularNotes} onChange={update("cardiovascularNotes")} /></Field><Field label="Neurological history"><Textarea value={form.neurologicalNotes} onChange={update("neurologicalNotes")} /></Field><Field label="Previous surgeries"><Textarea value={form.surgeries} onChange={update("surgeries")} /></Field><Field label="Tobacco use"><Textarea value={form.tobaccoUse} onChange={update("tobaccoUse")} /></Field><Field label="Family medical history"><Textarea value={form.familyMedicalHistory} onChange={update("familyMedicalHistory")} /></Field><Field label="Family ocular history"><Textarea value={form.familyOcularHistory} onChange={update("familyOcularHistory")} /></Field><Field label="Previous eye surgery"><Textarea value={form.previousEyeSurgery} onChange={update("previousEyeSurgery")} /></Field><Field label="Ocular trauma"><Textarea value={form.ocularTrauma} onChange={update("ocularTrauma")} /></Field><Field label="Glaucoma history"><Textarea value={form.glaucomaHistory} onChange={update("glaucomaHistory")} /></Field><Field label="Cataract history"><Textarea value={form.cataractHistory} onChange={update("cataractHistory")} /></Field><Field label="Retinal disease"><Textarea value={form.retinalDisease} onChange={update("retinalDisease")} /></Field><Field label="Pregnancy (when relevant)"><Textarea value={form.pregnancyNotes} onChange={update("pregnancyNotes")} /></Field><Field label="Previous glasses"><Textarea value={form.previousGlasses} onChange={update("previousGlasses")} /></Field><Field label="Previous contact lenses"><Textarea value={form.previousContactLenses} onChange={update("previousContactLenses")} /></Field></div>{conflict && <ConflictNotice />}<DialogFooter><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save history"}</Button></DialogFooter></form></DialogContent>;
}

function TriState({ label, value, onChange }: { label: string; value: boolean | null; onChange(value: boolean | null): void }) {
  return <Field label={label}><Select value={value === null ? "unknown" : value ? "yes" : "no"} onChange={(event) => onChange(event.target.value === "unknown" ? null : event.target.value === "yes")}><option value="unknown">Unknown / not assessed</option><option value="no">No</option><option value="yes">Yes</option></Select></Field>;
}

function ConflictNotice() { return <div role="alert" className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>This history changed on another device.</strong><p>Close, reload and review the latest history before saving.</p></div>; }
