import * as React from "react";
import { Minus, Plus, Search, ShoppingCart, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "../api";
import { useLoad } from "../hooks";
import { money } from "../lib";
import type { InventoryItem } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { EmptyState, ErrorState, Skeleton } from "../components/ui/data";
import { Field, FieldGroup, Input, Select } from "../components/ui/input";
import { PatientPicker } from "../components/patient-search";

interface CartLine { item: InventoryItem; quantity: number }
export function POSPage() {
  const inventory = useLoad(() => api.get<{ items: InventoryItem[] }>("/inventory")); const methods = useLoad(() => api.get<{ items: { id: string; name: string }[] }>("/payment-methods")); const register = useLoad(() => api.get<{ open: boolean; id?: string }>("/cash-register"));
  const [query, setQuery] = React.useState(""); const [cart, setCart] = React.useState<CartLine[]>([]); const [patientId, setPatientId] = React.useState(""); const [method, setMethod] = React.useState("pm_cash"); const [amount, setAmount] = React.useState<number | null>(null); const [saving, setSaving] = React.useState(false);
  const visible = inventory.data?.items.filter((item) => `${item.sku} ${item.barcode} ${item.name} ${item.brand}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  const currency = cart[0]?.item.currency ?? "HTG"; const total = cart.reduce((sum, line) => sum + line.item.salePriceMinor * line.quantity, 0); const payment = amount ?? total;
  const add = (item: InventoryItem) => setCart((current) => { if (current.length && current[0].item.currency !== item.currency) { toast.error("Complete this sale before adding an item in another currency."); return current; } const existing = current.find((line) => line.item.id === item.id); return existing ? current.map((line) => line.item.id === item.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { item, quantity: 1 }]; });
  const change = (id: string, delta: number) => setCart((current) => current.map((line) => line.item.id === id ? { ...line, quantity: Math.max(0, line.quantity + delta) } : line).filter((line) => line.quantity > 0));
  const checkout = async () => { setSaving(true); try { const result = await api.post<{ invoiceNumber: string; receiptNumber: string; balanceMinor: number }>("/pos/checkout", { invoice: { patientId, currency, exchangeRate: "1", discountMinor: 0, taxMinor: 0, dueAt: "", notes: "POS sale", items: cart.map((line) => ({ inventoryItemId: line.item.id, description: line.item.name, quantity: line.quantity, unitPriceMinor: line.item.salePriceMinor, discountMinor: 0, taxMinor: 0 })) }, payment: payment > 0 ? { paymentMethodId: method, registerSessionId: register.data?.id ?? "", amountMinor: payment, currency, exchangeRate: "1", reference: "", notes: "" } : null }); toast.success(`${result.invoiceNumber} created${result.receiptNumber ? ` · ${result.receiptNumber}` : ""}`); setCart([]); setAmount(null); inventory.reload(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Checkout failed"); } finally { setSaving(false); } };
  return <div className="page"><div><p className="section-title">Transactional checkout</p><h1 className="page-title">Point of Sale</h1><p className="page-description">Invoice, payment and stock deduction commit together or roll back together.</p></div><div className="mt-6 grid gap-4 xl:grid-cols-[1fr_420px]"><Card><CardHeader><CardTitle>Products & services</CardTitle><CardDescription>Search by name, SKU or barcode</CardDescription></CardHeader><CardContent><div className="relative mb-4"><Search className="absolute left-3 top-3.5 h-4 w-4 text-zinc-400" /><Input className="pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Scan barcode or search catalog…" /></div>{inventory.loading ? <Skeleton className="h-72" /> : inventory.error ? <ErrorState message={inventory.error.message} retry={inventory.reload} /> : visible.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map((item) => <button key={item.id} onClick={() => add(item)} disabled={item.trackStock && item.quantity <= 0} className="rounded-lg border p-4 text-left hover:border-black disabled:cursor-not-allowed disabled:opacity-40"><div className="font-mono text-[10px] font-bold text-zinc-500">{item.sku}</div><div className="mt-1 font-semibold">{item.name}</div><div className="mt-4 flex items-end justify-between"><span className="font-mono font-bold">{money(item.salePriceMinor, item.currency)}</span><span className="text-xs text-zinc-500">{item.trackStock ? `${item.quantity} in stock` : "Service"}</span></div></button>)}</div> : <EmptyState title="No matching items" description="Change your search or add items in Inventory." />}</CardContent></Card>
      <Card className="h-fit xl:sticky xl:top-20"><CardHeader><CardTitle className="flex items-center gap-2"><ShoppingCart className="h-4 w-4" />Current sale</CardTitle><CardDescription>{cart.reduce((sum, line) => sum + line.quantity, 0)} line units</CardDescription></CardHeader><CardContent>{cart.length ? <div className="space-y-3">{cart.map((line) => <div key={line.item.id} className="flex items-center gap-3 border-b pb-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{line.item.name}</div><div className="font-mono text-xs text-zinc-500">{money(line.item.salePriceMinor, line.item.currency)}</div></div><div className="flex items-center rounded-md border"><button aria-label={`Decrease ${line.item.name}`} className="grid h-11 w-11 place-items-center sm:h-9 sm:w-9" onClick={() => change(line.item.id, -1)}><Minus className="h-3 w-3" /></button><span className="w-8 text-center font-mono text-xs">{line.quantity}</span><button aria-label={`Increase ${line.item.name}`} className="grid h-11 w-11 place-items-center sm:h-9 sm:w-9" onClick={() => change(line.item.id, 1)}><Plus className="h-3 w-3" /></button></div><button aria-label="Remove" className="grid h-11 w-11 place-items-center text-zinc-400 hover:text-red-700 sm:h-9 sm:w-9" onClick={() => setCart(cart.filter((candidate) => candidate.item.id !== line.item.id))}><Trash2 className="h-4 w-4" /></button></div>)}<FieldGroup label="Patient / customer" hint="Leave empty for an anonymous retail customer"><PatientPicker value={patientId} onChange={setPatientId} placeholder="Search patient, or leave empty…" /></FieldGroup><div className="grid gap-3 sm:grid-cols-2"><Field label="Payment method"><Select value={method} onChange={(event) => setMethod(event.target.value)}>{methods.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label={`Pay now (${currency} minor units)`}><Input type="number" min={0} max={total} value={amount ?? total} onChange={(event) => setAmount(Number(event.target.value))} /></Field></div><div className="flex items-center justify-between border-y py-4"><span className="font-semibold">Total</span><span className="font-mono text-2xl font-bold">{money(total,currency)}</span></div><Button className="w-full" disabled={saving || cart.length === 0 || payment > total} onClick={checkout}>{saving ? "Completing transaction…" : payment < total ? `Pay ${money(payment,currency)} · Balance ${money(total-payment,currency)}` : `Complete sale · ${money(total,currency)}`}</Button></div> : <EmptyState title="Cart is empty" description="Select a product or clinic service to begin." />}</CardContent></Card></div></div>;
}
