import { Download, FileText, Printer } from "lucide-react";
import { api } from "../api";
import { useLoad } from "../hooks";
import { dateTime } from "../lib";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Badge, EmptyState, ErrorState, Skeleton, Table, Td, Th } from "../components/ui/data";

interface Prescription { id:string;prescriptionNumber:string;patientName:string;type:string;od:Record<string,string>;os:Record<string,string>;details:Record<string,string>;notes:string;issuedAt:string;expiresAt:string;doctor:string }
export function PrescriptionsPage(){const prescriptions=useLoad(()=>api.get<{items:Prescription[]}>("/prescriptions"));return <div className="page"><div><p className="section-title">Clinical documents</p><h1 className="page-title">Prescriptions</h1><p className="page-description">Doctor-issued spectacle, contact lens and medication prescriptions.</p></div><Card className="mt-6"><CardHeader><CardTitle>Prescription register</CardTitle><CardDescription>Print uses the clinic identity configured in Settings.</CardDescription></CardHeader><CardContent>{prescriptions.loading?<Skeleton className="h-72"/>:prescriptions.error?<ErrorState message={prescriptions.error.message} retry={prescriptions.reload}/>:prescriptions.data?.items.length?<Table><thead><tr><Th>Prescription</Th><Th>Patient</Th><Th>Type</Th><Th>Issued</Th><Th>Doctor</Th><Th>Action</Th></tr></thead><tbody>{prescriptions.data.items.map((item)=><tr key={item.id}><Td className="font-mono text-xs font-bold">{item.prescriptionNumber}</Td><Td>{item.patientName}</Td><Td><Badge>{item.type.replaceAll("_"," ")}</Badge></Td><Td>{dateTime(item.issuedAt)}</Td><Td>{item.doctor}</Td><Td><Button size="sm" variant="outline" onClick={()=>window.print()}><Printer className="h-3 w-3"/>Print</Button></Td></tr>)}</tbody></Table>:<EmptyState title="No prescriptions" description="Doctor-issued prescriptions appear here."/>}</CardContent></Card></div>}
interface DocumentItem{id:string;patientId:string;category:string;displayName:string;mediaType:string;sizeBytes:number;createdAt:string}
export function DocumentsPage(){const documents=useLoad(()=>api.get<{items:DocumentItem[]}>("/documents"));return <div className="page"><div><p className="section-title">Local file storage</p><h1 className="page-title">Documents</h1><p className="page-description">Files live on the clinic server filesystem; metadata stays in SQLite.</p></div><Card className="mt-6"><CardHeader><CardTitle>Patient documents</CardTitle><CardDescription>Upload new files from the patient profile.</CardDescription></CardHeader><CardContent>{documents.loading?<Skeleton className="h-72"/>:documents.error?<ErrorState message={documents.error.message} retry={documents.reload}/>:documents.data?.items.length?<div className="divide-y">{documents.data.items.map((item)=><div className="flex items-center gap-3 py-3" key={item.id}><div className="grid h-10 w-10 place-items-center rounded-md bg-zinc-100"><FileText className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="truncate font-semibold">{item.displayName}</div><div className="text-xs text-zinc-500">{item.category} · {(item.sizeBytes/1024).toFixed(1)} KB · {dateTime(item.createdAt)}</div></div><Button variant="outline" size="sm" asChild><a href={`/api/v1/documents/${item.id}/download`}><Download className="h-3 w-3"/>Download</a></Button></div>)}</div>:<EmptyState title="No documents" description="PDF, JPG, PNG, DOC and DOCX files uploaded from patient charts appear here."/>}</CardContent></Card></div>}

