import * as React from "react";
import { Download, Printer, RefreshCw } from "lucide-react";
import { api } from "../api";
import { useLoad } from "../hooks";
import { money, todayInput } from "../lib";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { EmptyState, ErrorState, Skeleton, Table, Td, Th } from "../components/ui/data";
import { Field, Input, Select } from "../components/ui/input";
import { PrintHeader, triggerPrint } from "../components/print";

interface Report { report: string; from: string; to: string; items: { label: string; count: number; amountMinor: number }[] }
export function ReportsPage(){const [report,setReport]=React.useState("sales");const [from,setFrom]=React.useState(new Date(Date.now()-30*86400000).toISOString().slice(0,10));const [to,setTo]=React.useState(todayInput());const data=useLoad(()=>api.get<Report>(`/reports/${report}?from=${from}&to=${to}`),[report,from,to]);return <div className="page"><div className="no-print"><p className="section-title">Operational analytics</p><h1 className="page-title">Reports</h1><p className="page-description">Live SQLite reports with CSV and branded print/PDF output.</p></div><Card className="mt-6 print-area"><CardHeader><div className="no-print grid gap-3 sm:grid-cols-4 sm:items-end"><Field label="Report"><Select value={report} onChange={(event)=>setReport(event.target.value)}><option value="sales">Sales by day</option><option value="patients">New patients</option><option value="appointments">Appointment status</option><option value="clinical">Consultations</option><option value="inventory">Inventory valuation</option><option value="lab">Lab order status</option></Select></Field><Field label="From"><Input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/></Field><Field label="To"><Input type="date" value={to} onChange={(event)=>setTo(event.target.value)}/></Field><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={data.reload}><RefreshCw className="h-4 w-4"/>Refresh</Button><Button variant="outline" onClick={triggerPrint}><Printer className="h-4 w-4"/>Print</Button><Button asChild><a href={`/api/v1/reports/${report}?from=${from}&to=${to}&format=csv`}><Download className="h-4 w-4"/>CSV</a></Button></div></div><div className="hidden print:block"><PrintHeader documentTitle="Clinic report" number={report.toUpperCase()} date={`${from} — ${to}`} /></div><CardTitle className="mt-5 capitalize">{report} report</CardTitle><CardDescription>{from} through {to}</CardDescription></CardHeader><CardContent>{data.loading?<Skeleton className="h-72"/>:data.error?<ErrorState message={data.error.message} retry={data.reload}/>:data.data?.items.length?<Table><thead><tr><Th>Category / date</Th><Th>Count</Th><Th>Amount / valuation</Th></tr></thead><tbody>{data.data.items.map((item)=><tr key={item.label}><Td className="font-semibold capitalize">{item.label.replaceAll("_"," ")}</Td><Td className="font-mono">{item.count}</Td><Td className="font-mono font-bold">{item.amountMinor?money(item.amountMinor):"—"}</Td></tr>)}</tbody></Table>:<EmptyState title="No report data" description="No matching records exist in this date range."/>}</CardContent></Card></div>}
