import * as React from "react";
import { useNavigate } from "react-router-dom";
import { CalendarPlus, Check, ChevronLeft, ChevronRight, Pencil } from "lucide-react";
import { toast } from "sonner";
import { api } from "../api";
import { useLoad } from "../hooks";
import { todayInput } from "../lib";
import { useRealtime } from "../realtime";
import type { Appointment } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "../components/ui/dialog";
import { EmptyState, ErrorState, Skeleton } from "../components/ui/data";
import { Field, Input, Select, Textarea } from "../components/ui/input";
import { DateTimeInput } from "../components/ui/date-time";
import { PatientPicker } from "../components/patient-search";
import { WaitingRoomScreen } from "../components/waiting-room";
import { StatusLegend, StatusPill, statusAppearance, stripedBackground } from "../components/status";

type CalendarView = "day" | "week" | "month";
const terminalStatuses = ["cancelled", "completed", "no_show"];

function localDate(value: string) { const [year, month, day] = value.split("-").map(Number); return new Date(year, month - 1, day); }
function dateInput(value: Date) { const copy = new Date(value); copy.setMinutes(copy.getMinutes() - copy.getTimezoneOffset()); return copy.toISOString().slice(0, 10); }
function startOfWeek(value: Date) { const result = new Date(value); const offset = (result.getDay() + 6) % 7; result.setDate(result.getDate() - offset); result.setHours(0, 0, 0, 0); return result; }
function addDays(value: Date, count: number) { const result = new Date(value); result.setDate(result.getDate() + count); return result; }
function rangeFor(view: CalendarView, anchor: string) { const selected = localDate(anchor); let from: Date; let to: Date; if (view === "day") { from = selected; to = addDays(selected, 1); } else if (view === "week") { from = startOfWeek(selected); to = addDays(from, 7); } else { from = new Date(selected.getFullYear(), selected.getMonth(), 1); to = new Date(selected.getFullYear(), selected.getMonth() + 1, 1); } return { from: from.toISOString(), to: to.toISOString() }; }
function heading(view: CalendarView, anchor: string) { const selected = localDate(anchor); if (view === "day") return selected.toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric", year: "numeric" }); if (view === "week") { const start = startOfWeek(selected), end = addDays(start, 6); return `${start.toLocaleDateString(undefined, { month: "short", day: "numeric" })} – ${end.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`; } return selected.toLocaleDateString(undefined, { month: "long", year: "numeric" }); }

export function SchedulePage() {
  const { revision } = useRealtime();
  const navigate = useNavigate();
  const [date, setDate] = React.useState(todayInput());
  const [view, setView] = React.useState<CalendarView>(() => window.innerWidth < 640 ? "day" : "week");
  // The front desk lives on the waiting room, so it gets the whole screen
  // rather than a narrow column beside the calendar.
  const [screen, setScreen] = React.useState<"calendar" | "waiting">("calendar");
  const [appointmentOpen, setAppointmentOpen] = React.useState(false);
  const [selected, setSelected] = React.useState<Appointment | null>(null);
  const range = rangeFor(view, date);
  const appointments = useLoad(() => api.get<{ items: Appointment[] }>(`/appointments?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`), [range.from, range.to, revision]);
  const move = (direction: number) => { const current = localDate(date); if (view === "day") current.setDate(current.getDate() + direction); else if (view === "week") current.setDate(current.getDate() + direction * 7); else current.setMonth(current.getMonth() + direction); setDate(dateInput(current)); };
  return <div className="page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-title">Patient flow</p><h1 className="page-title">Appointments & waiting room</h1><p className="page-description">Responsive day, week and month scheduling with live patient flow.</p></div><div className="flex flex-wrap gap-2"><div className="flex rounded-md border bg-zinc-50 p-0.5">{([["calendar", "Calendar"], ["waiting", "Waiting room"]] as const).map(([option, label]) => <Button key={option} size="sm" variant={screen === option ? "default" : "ghost"} aria-pressed={screen === option} onClick={() => setScreen(option)}>{label}</Button>)}</div><Dialog open={appointmentOpen} onOpenChange={setAppointmentOpen}><DialogTrigger asChild><Button><CalendarPlus className="h-4 w-4" />New appointment</Button></DialogTrigger><AppointmentForm defaultDate={date} onSaved={() => { setAppointmentOpen(false); appointments.reload(); }} /></Dialog></div></div>
    {screen === "waiting" ? <section className="mt-6"><WaitingRoomScreen onOpenPatient={(patientId) => navigate(`/patients?id=${patientId}`)} /></section> : <section className="mt-6 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card className="min-w-0"><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle>{heading(view, date)}</CardTitle><CardDescription>{appointments.data?.items.length ?? 0} appointments in this view</CardDescription></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-md border"><Button aria-label="Previous period" size="icon" variant="ghost" onClick={() => move(-1)}><ChevronLeft className="h-4 w-4" /></Button><Button variant="ghost" onClick={() => setDate(todayInput())}>Today</Button><Button aria-label="Next period" size="icon" variant="ghost" onClick={() => move(1)}><ChevronRight className="h-4 w-4" /></Button></div><Input className="w-auto" type="date" value={date} onChange={(event) => setDate(event.target.value)} /><div className="flex rounded-md border bg-zinc-50 p-0.5">{(["day", "week", "month"] as CalendarView[]).map((option) => <Button key={option} size="sm" variant={view === option ? "default" : "ghost"} onClick={() => setView(option)}>{option}</Button>)}</div></div></div><StatusLegend className="mt-3" /></CardHeader><CardContent>{appointments.loading ? <Skeleton className="h-[34rem]" /> : appointments.error ? <ErrorState message={appointments.error.message} retry={appointments.reload} /> : <CalendarViewPanel view={view} anchor={date} appointments={appointments.data?.items ?? []} onOpen={setSelected} />}</CardContent></Card>
      <WaitingRoomScreen onOpenPatient={(patientId) => navigate(`/patients?id=${patientId}`)} /></section>}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}>{selected && <AppointmentDetail appointment={selected} onChanged={() => { setSelected(null); appointments.reload(); }} />}</Dialog>
  </div>;
}

function CalendarViewPanel({ view, anchor, appointments, onOpen }: { view: CalendarView; anchor: string; appointments: Appointment[]; onOpen(value: Appointment): void }) {
  if (view === "day") return <AppointmentAgenda appointments={appointments} onOpen={onOpen} />;
  const selected = localDate(anchor);
  if (view === "week") { const start = startOfWeek(selected); const days = Array.from({ length: 7 }, (_, index) => addDays(start, index)); return <><div className="hidden grid-cols-7 divide-x rounded-lg border md:grid">{days.map((day) => { const items = appointments.filter((appointment) => dateInput(new Date(appointment.startsAt)) === dateInput(day)); return <div className="min-h-[30rem] min-w-0" key={day.toISOString()}><div className={`border-b p-2 text-center ${dateInput(day) === todayInput() ? "bg-black text-white" : "bg-zinc-50"}`}><div className="text-[10px] font-bold uppercase">{day.toLocaleDateString(undefined, { weekday: "short" })}</div><div className="font-mono text-lg font-bold">{day.getDate()}</div></div><div className="space-y-2 p-1.5">{items.map((item) => <AppointmentChip key={item.id} item={item} onOpen={onOpen} />)}</div></div>; })}</div><div className="space-y-4 md:hidden">{days.map((day) => <DayGroup key={day.toISOString()} day={day} items={appointments.filter((appointment) => dateInput(new Date(appointment.startsAt)) === dateInput(day))} onOpen={onOpen} />)}</div></>; }
  const first = new Date(selected.getFullYear(), selected.getMonth(), 1); const daysInMonth = new Date(selected.getFullYear(), selected.getMonth() + 1, 0).getDate(); const leading = (first.getDay() + 6) % 7;
  return <><div className="hidden grid-cols-7 overflow-hidden rounded-lg border md:grid"><div className="col-span-7 grid grid-cols-7 border-b bg-zinc-50">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div className="p-2 text-center text-[10px] font-bold uppercase text-zinc-500" key={day}>{day}</div>)}</div>{Array.from({ length: leading }, (_, index) => <div className="min-h-28 border-b border-r bg-zinc-50/50" key={`blank-${index}`} />)}{Array.from({ length: daysInMonth }, (_, index) => { const day = new Date(selected.getFullYear(), selected.getMonth(), index + 1); const items = appointments.filter((appointment) => dateInput(new Date(appointment.startsAt)) === dateInput(day)); return <div className="min-h-28 min-w-0 border-b border-r p-1.5" key={day.toISOString()}><div className={`mb-1 grid h-6 w-6 place-items-center rounded-full font-mono text-xs font-bold ${dateInput(day) === todayInput() ? "bg-black text-white" : ""}`}>{day.getDate()}</div>{items.slice(0, 3).map((item) => { const appearance = statusAppearance(item.status); const { Icon } = appearance; return <button className={`mb-1 flex w-full items-center gap-1 truncate rounded border px-1.5 py-1 text-left text-[10px] font-semibold ${appearance.chipClassName}`} style={appearance.striped ? { backgroundImage: stripedBackground } : undefined} title={`${appearance.label} · ${item.patientName}`} key={item.id} onClick={() => onOpen(item)}><Icon aria-hidden className="h-2.5 w-2.5 shrink-0" /><span className="truncate">{new Date(item.startsAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} {item.patientName}</span></button>; })}{items.length > 3 && <div className="text-[10px] text-zinc-500">+{items.length - 3} more</div>}</div>; })}</div><div className="space-y-4 md:hidden">{Array.from({ length: daysInMonth }, (_, index) => new Date(selected.getFullYear(), selected.getMonth(), index + 1)).filter((day) => appointments.some((appointment) => dateInput(new Date(appointment.startsAt)) === dateInput(day))).map((day) => <DayGroup key={day.toISOString()} day={day} items={appointments.filter((appointment) => dateInput(new Date(appointment.startsAt)) === dateInput(day))} onOpen={onOpen} />)}{appointments.length === 0 && <EmptyState title="No appointments" description="No appointments are scheduled for this month." />}</div></>;
}

function AppointmentAgenda({ appointments, onOpen }: { appointments: Appointment[]; onOpen(value: Appointment): void }) { return appointments.length ? <div className="grid gap-2">{appointments.map((item) => { const appearance = statusAppearance(item.status); return <button key={item.id} className={`grid w-full gap-3 rounded-md py-4 pl-3 pr-2 text-left sm:grid-cols-[80px_1fr_auto] sm:items-center ${appearance.edgeClassName} hover:bg-zinc-50`} onClick={() => onOpen(item)}><div className="font-mono text-sm font-bold">{new Date(item.startsAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div><div><div className="font-semibold">{item.patientName}</div><div className="mt-1 text-xs text-zinc-500">{item.reason || item.type.replaceAll("_", " ")} · {item.durationMinutes} min</div></div><StatusPill appearance={appearance} /></button>; })}</div> : <EmptyState title="No appointments" description="No appointments are scheduled for this period." />; }
function AppointmentChip({ item, onOpen }: { item: Appointment; onOpen(value: Appointment): void }) { const appearance = statusAppearance(item.status); const { Icon } = appearance; return <button className={`w-full rounded-md border p-2 text-left shadow-sm hover:brightness-95 ${appearance.chipClassName}`} style={appearance.striped ? { backgroundImage: stripedBackground } : undefined} onClick={() => onOpen(item)}><div className="font-mono text-[10px] font-bold">{new Date(item.startsAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div><div className="truncate text-xs font-semibold">{item.patientName}</div><div className="mt-1 flex items-center gap-1 truncate text-[10px] font-semibold"><Icon aria-hidden className="h-2.5 w-2.5 shrink-0" />{appearance.label}</div></button>; }
function DayGroup({ day, items, onOpen }: { day: Date; items: Appointment[]; onOpen(value: Appointment): void }) { return <section><div className="mb-2 flex items-center gap-2"><div className={`grid h-9 w-9 place-items-center rounded-full font-mono text-sm font-bold ${dateInput(day) === todayInput() ? "bg-black text-white" : "bg-zinc-100"}`}>{day.getDate()}</div><div className="text-sm font-bold">{day.toLocaleDateString(undefined, { weekday: "long", month: "long" })}</div></div>{items.length ? <div className="space-y-2">{items.map((item) => <AppointmentChip key={item.id} item={item} onOpen={onOpen} />)}</div> : <div className="rounded-md border border-dashed p-3 text-sm text-zinc-400">No appointments</div>}</section>; }

function AppointmentDetail({ appointment, onChanged }: { appointment: Appointment; onChanged(): void }) {
  const [editing, setEditing] = React.useState(false);
  const status = async (value: string) => { try { await api.patch(`/appointments/${appointment.id}/status`, { status: value, version: appointment.version }); toast.success(`Appointment marked ${value.replaceAll("_", " ")}`); onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not update appointment"); } };
  if (editing) return <AppointmentForm appointment={appointment} onSaved={onChanged} />;
  return <DialogContent><DialogHeader><DialogTitle>{appointment.patientName}</DialogTitle><DialogDescription>{new Date(appointment.startsAt).toLocaleString()} · {appointment.durationMinutes} minutes</DialogDescription></DialogHeader><div className="grid gap-3"><div className="flex items-center justify-between rounded-md border p-3"><span className="text-sm font-semibold">Status</span><StatusPill appearance={statusAppearance(appointment.status)} /></div><div className="rounded-md bg-zinc-50 p-3 text-sm"><strong>{appointment.type.replaceAll("_", " ")}</strong><p className="mt-1 text-zinc-600">{appointment.reason || "No reason provided"}</p>{appointment.notes && <p className="mt-2 text-zinc-500">{appointment.notes}</p>}</div></div><DialogFooter><Button variant="outline" onClick={() => setEditing(true)} disabled={terminalStatuses.includes(appointment.status)}><Pencil className="h-4 w-4" />Reschedule</Button>{appointment.status === "scheduled" && <Button variant="outline" onClick={() => status("confirmed")}>Confirm</Button>}{!terminalStatuses.includes(appointment.status) && <Button variant="outline" onClick={() => status("cancelled")}>Cancel</Button>}{!terminalStatuses.includes(appointment.status) && <Button variant="outline" onClick={() => status("no_show")}>No show</Button>}{!terminalStatuses.includes(appointment.status) && <Button onClick={async () => { try { await api.post("/queue/check-in", { patientId: appointment.patientId, appointmentId: appointment.id, assignedDoctorId: appointment.practitionerId, priority: 0 }); toast.success("Patient checked in"); onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Check-in failed"); } }}><Check className="h-4 w-4" />Check in</Button>}</DialogFooter></DialogContent>;
}

// Was a <select> populated by /patients?limit=100, which could not reach patient
// 101 of 5,000. It now searches the server as the user types.
function PatientSelect({ value, onChange }: { value: string; onChange(value: string): void }) {
  return <PatientPicker required value={value} onChange={onChange} />;
}

function toLocalDateTime(value: string) { const date = new Date(value); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
function AppointmentForm({ onSaved, appointment, defaultDate = todayInput() }: { onSaved(): void; appointment?: Appointment; defaultDate?: string }) {
  const [form, setForm] = React.useState({ patientId: appointment?.patientId ?? "", startsAt: appointment ? toLocalDateTime(appointment.startsAt) : `${defaultDate}T09:00`, durationMinutes: appointment?.durationMinutes ?? 30, type: appointment?.type ?? "eye_exam", reason: appointment?.reason ?? "", notes: appointment?.notes ?? "", practitionerId: appointment?.practitionerId ?? "", version: appointment?.version ?? 0 }); const [saving, setSaving] = React.useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const body = { ...form, startsAt: new Date(form.startsAt).toISOString() }; appointment ? await api.put(`/appointments/${appointment.id}`, body) : await api.post("/appointments", body); toast.success(appointment ? "Appointment rescheduled" : "Appointment created"); onSaved(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not save appointment"); } finally { setSaving(false); } };
  return <DialogContent><DialogHeader><DialogTitle>{appointment ? "Reschedule appointment" : "Create appointment"}</DialogTitle><DialogDescription>Scheduling conflicts are checked by the clinic server.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Patient"><PatientSelect value={form.patientId} onChange={(patientId) => setForm({ ...form, patientId })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Start"><DateTimeInput label="Start" value={form.startsAt} onChange={(startsAt) => setForm({ ...form, startsAt })} required /></Field><Field label="Duration (minutes)"><Input type="number" min={10} max={240} value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: Number(event.target.value) })} /></Field></div><Field label="Visit type"><Select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="eye_exam">Eye examination</option><option value="follow_up">Follow-up</option><option value="contact_lens">Contact lens</option><option value="optical_delivery">Optical delivery</option></Select></Field><Field label="Reason"><Input value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></Field><Field label="Notes"><Textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></Field><DialogFooter><Button type="submit" disabled={saving}>{saving ? "Saving…" : appointment ? "Save new time" : "Create appointment"}</Button></DialogFooter></form></DialogContent>;
}
