import * as React from "react";
import { CalendarPlus, Check, Clock3, Play, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { api } from "../api";
import { useLoad } from "../hooks";
import { dateTime, todayInput } from "../lib";
import { useRealtime } from "../realtime";
import type { Appointment, Patient, QueueEntry } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "../components/ui/dialog";
import { Badge, EmptyState, ErrorState, Skeleton } from "../components/ui/data";
import { Field, Input, Select, Textarea } from "../components/ui/input";

const stages = ["waiting_nurse", "pre_test", "waiting_doctor", "in_consultation", "checkout", "completed"];
export function SchedulePage() {
  const { revision } = useRealtime(); const [date, setDate] = React.useState(todayInput()); const [appointmentOpen, setAppointmentOpen] = React.useState(false); const [checkInOpen, setCheckInOpen] = React.useState(false); const [, tick] = React.useState(0);
  React.useEffect(() => { const timer = setInterval(() => tick((value) => value + 1), 30000); return () => clearInterval(timer); }, []);
  const appointments = useLoad(() => api.get<{ items: Appointment[] }>(`/appointments?date=${date}`), [date, revision]);
  const queue = useLoad(() => api.get<{ items: QueueEntry[] }>("/queue"), [revision]);
  const reload = () => { appointments.reload(); queue.reload(); };
  const changeStage = async (entry: QueueEntry, stage: string) => { try { await api.patch(`/queue/${entry.id}`, { stage, priority: entry.priority, assignedDoctorId: entry.assignedDoctorId, version: entry.version }); toast.success(`Moved to ${stage.replaceAll("_", " ")}`); reload(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Queue update failed"); } };
  return <div className="page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-title">Patient flow</p><h1 className="page-title">Appointments & waiting room</h1><p className="page-description">Schedule visits, accept walk-ins and move patients through the live queue.</p></div><div className="flex gap-2"><Dialog open={checkInOpen} onOpenChange={setCheckInOpen}><DialogTrigger asChild><Button variant="outline"><UserPlus className="h-4 w-4" />Walk-in</Button></DialogTrigger><CheckInForm onSaved={() => { setCheckInOpen(false); reload(); }} /></Dialog><Dialog open={appointmentOpen} onOpenChange={setAppointmentOpen}><DialogTrigger asChild><Button><CalendarPlus className="h-4 w-4" />New appointment</Button></DialogTrigger><AppointmentForm onSaved={() => { setAppointmentOpen(false); reload(); }} /></Dialog></div></div>
    <section className="mt-6 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Appointment agenda</CardTitle><CardDescription>{appointments.data?.items.length ?? 0} scheduled records</CardDescription></div><Input className="w-auto" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></CardHeader><CardContent>{appointments.loading ? <Skeleton className="h-80" /> : appointments.error ? <ErrorState message={appointments.error.message} retry={appointments.reload} /> : appointments.data?.items.length ? <div className="divide-y">{appointments.data.items.map((item) => <div key={item.id} className="grid gap-3 py-4 sm:grid-cols-[70px_1fr_auto] sm:items-center"><div className="font-mono text-sm font-bold">{new Date(item.startsAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div><div><div className="font-semibold">{item.patientName}</div><div className="mt-1 text-xs text-zinc-500">{item.reason || item.type} · {item.durationMinutes} min</div></div><div className="flex items-center gap-2"><Badge>{item.status.replaceAll("_", " ")}</Badge>{!['cancelled','completed','no_show'].includes(item.status) && <Button size="sm" variant="outline" onClick={async () => { try { await api.post("/queue/check-in", { patientId: item.patientId, appointmentId: item.id, assignedDoctorId: item.practitionerId, priority: 0 }); toast.success("Patient checked in"); reload(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Check-in failed"); } }}><Check className="h-3 w-3" />Check in</Button>}</div></div>)}</div> : <EmptyState title="No appointments" description="No appointments are scheduled for this date." />}</CardContent></Card>
      <Card><CardHeader><CardTitle>Live waiting room</CardTitle><CardDescription>Timers update while this screen is open</CardDescription></CardHeader><CardContent>{queue.loading ? <Skeleton className="h-80" /> : queue.error ? <ErrorState message={queue.error.message} retry={queue.reload} /> : queue.data?.items.length ? <div className="space-y-3">{queue.data.items.map((entry) => { const next = stages[Math.min(stages.indexOf(entry.stage) + 1, stages.length - 1)]; const wait = Math.max(0, Math.floor((Date.now() - new Date(entry.arrivedAt).getTime()) / 60000)); return <div key={entry.id} className="rounded-lg border border-zinc-200 p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-zinc-100 text-xs font-bold">{entry.patientName.split(" ").map((part) => part[0]).slice(0,2).join("")}</div><div className="min-w-0 flex-1"><div className="font-semibold">{entry.patientName}</div><div className="mt-1 flex items-center gap-1 font-mono text-xs text-zinc-500"><Clock3 className="h-3 w-3" />{wait} min · {entry.medicalRecordNumber}</div></div><Badge tone={wait > 30 ? "warning" : "neutral"}>{entry.stage.replaceAll("_", " ")}</Badge></div>{entry.stage !== "completed" && <Button className="mt-3 w-full" size="sm" variant="outline" onClick={() => changeStage(entry, next)}><Play className="h-3 w-3" />Move to {next.replaceAll("_", " ")}</Button>}</div>; })}</div> : <EmptyState title="Waiting room is clear" description="Check in an appointment or add a walk-in patient." />}</CardContent></Card></section>
  </div>;
}

function PatientSelect({ value, onChange }: { value: string; onChange(value: string): void }) { const patients = useLoad(() => api.get<{ items: Patient[] }>("/patients?limit=100")); return <Select required value={value} onChange={(event) => onChange(event.target.value)}><option value="">Select patient…</option>{patients.data?.items.map((patient) => <option value={patient.id} key={patient.id}>{patient.medicalRecordNumber} — {patient.firstName} {patient.lastName}</option>)}</Select>; }

function AppointmentForm({ onSaved }: { onSaved(): void }) {
  const [form, setForm] = React.useState({ patientId: "", startsAt: `${todayInput()}T09:00`, durationMinutes: 30, type: "eye_exam", reason: "", notes: "" }); const [saving, setSaving] = React.useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.post("/appointments", { ...form, startsAt: new Date(form.startsAt).toISOString(), practitionerId: "" }); toast.success("Appointment created"); onSaved(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not create appointment"); } finally { setSaving(false); } };
  return <DialogContent><DialogHeader><DialogTitle>Create appointment</DialogTitle><DialogDescription>Scheduling conflicts are checked by the clinic server.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Patient"><PatientSelect value={form.patientId} onChange={(patientId) => setForm({ ...form, patientId })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Start"><Input type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} required /></Field><Field label="Duration (minutes)"><Input type="number" min={10} max={240} value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: Number(event.target.value) })} /></Field></div><Field label="Visit type"><Select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="eye_exam">Eye examination</option><option value="follow_up">Follow-up</option><option value="contact_lens">Contact lens</option><option value="optical_delivery">Optical delivery</option></Select></Field><Field label="Reason"><Input value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></Field><Field label="Notes"><Textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></Field><DialogFooter><Button type="submit" disabled={saving}>{saving ? "Creating…" : "Create appointment"}</Button></DialogFooter></form></DialogContent>;
}

function CheckInForm({ onSaved }: { onSaved(): void }) { const [patientId, setPatientId] = React.useState(""); const [priority, setPriority] = React.useState(0); const [saving, setSaving] = React.useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.post("/queue/check-in", { patientId, appointmentId: "", assignedDoctorId: "", priority }); toast.success("Walk-in added to waiting room"); onSaved(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Check-in failed"); } finally { setSaving(false); } }; return <DialogContent><DialogHeader><DialogTitle>Check in walk-in patient</DialogTitle><DialogDescription>An appointment is not required. Register a new patient first if necessary.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={submit}><Field label="Patient"><PatientSelect value={patientId} onChange={setPatientId} /></Field><Field label="Priority"><Select value={priority} onChange={(event) => setPriority(Number(event.target.value))}><option value={0}>Normal</option><option value={1}>Priority</option><option value={2}>Urgent</option></Select></Field><DialogFooter><Button type="submit" disabled={saving}>{saving ? "Checking in…" : "Add to waiting room"}</Button></DialogFooter></form></DialogContent>; }

