import * as React from "react";
import { CheckCircle2, ClipboardCheck, Eye, Plus, XCircle } from "lucide-react";
import { toast } from "sonner";
import { api } from "../api";
import { useAuth } from "../auth";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Badge, EmptyState, ErrorState, Skeleton } from "../components/ui/data";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "../components/ui/dialog";
import { Field, Input, Select, Textarea } from "../components/ui/input";
import { useLoad } from "../hooks";
import { useRealtime } from "../realtime";
import type { StockTake, StockTakeLine, StockTakeSummary } from "../types";

const takeTone = (status: string): "neutral" | "success" | "danger" => status === "completed" ? "success" : status === "cancelled" ? "danger" : "neutral";

export function StockTakesPage() {
  const { user } = useAuth(); const { revision } = useRealtime(); const [createOpen, setCreateOpen] = React.useState(false); const [selected, setSelected] = React.useState<string | null>(null);
  const takes = useLoad(() => api.get<{ items: StockTakeSummary[] }>("/stock-takes"), [revision]);
  return <div className="page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-title">Physical inventory control</p><h1 className="page-title">Stock takes</h1><p className="page-description">Count without changing stock, then let a doctor finalize audited corrections.</p></div>{user?.role === "doctor" && <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button><Plus className="h-4 w-4" />Start count</Button></DialogTrigger><StartStockTake onSaved={() => { setCreateOpen(false); takes.reload(); }} /></Dialog>}</div><Card className="mt-6 overflow-hidden">{takes.loading ? <div className="p-5"><Skeleton className="h-64" /></div> : takes.error ? <div className="p-5"><ErrorState message={takes.error.message} retry={takes.reload} /></div> : takes.data?.items.length ? <div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-3">{takes.data.items.map((take) => <button className="rounded-lg border p-4 text-left hover:border-black" key={take.id} onClick={() => setSelected(take.id)}><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-xs font-bold">{take.stockTakeNumber}</div><div className="mt-1 font-semibold capitalize">{take.category.replaceAll("_", " ") || "All inventory"}</div></div><Badge tone={takeTone(take.status)}>{take.status.replaceAll("_", " ")}</Badge></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-zinc-100"><div className="h-full bg-black" style={{ width: `${take.itemCount ? (take.countedCount / take.itemCount) * 100 : 0}%` }} /></div><div className="mt-2 flex justify-between text-xs text-zinc-500"><span>{take.countedCount}/{take.itemCount} counted</span><span>{take.differenceCount} differences</span></div></button>)}</div> : <EmptyState title="No physical counts" description={user?.role === "doctor" ? "Start a count to snapshot current expected quantities." : "A doctor must start a stock take before counts can be entered."} />}</Card><Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}>{selected && <StockTakeDetail id={selected} onChanged={takes.reload} />}</Dialog></div>;
}

function StartStockTake({ onSaved }: { onSaved(): void }) {
  const [category, setCategory] = React.useState(""); const [notes, setNotes] = React.useState(""); const [saving, setSaving] = React.useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.post("/stock-takes", { category, notes }); toast.success("Stock take started"); onSaved(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not start count"); } finally { setSaving(false); } };
  return <DialogContent><DialogHeader><DialogTitle>Start physical count</DialogTitle><DialogDescription>Expected quantities are snapshotted now. Complete the count before other stock movements.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={submit}><Field label="Category"><Select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All stock</option><option value="frame">Frames</option><option value="ophthalmic_lens">Ophthalmic lenses</option><option value="contact_lens">Contact lenses</option><option value="accessory">Accessories</option></Select></Field><Field label="Notes"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></Field><DialogFooter><Button type="submit" disabled={saving}>{saving ? "Starting…" : "Start count"}</Button></DialogFooter></form></DialogContent>;
}

function StockTakeDetail({ id, onChanged }: { id: string; onChanged(): void }) {
  const { user } = useAuth(); const take = useLoad(() => api.get<StockTake>(`/stock-takes/${id}`), [id]); const [drafts, setDrafts] = React.useState<Record<string, { count: string; reason: string }>>({}); const [saving, setSaving] = React.useState<string | null>(null);
  React.useEffect(() => { if (!take.data) return; const next: Record<string, { count: string; reason: string }> = {}; take.data.items.forEach((line) => { next[line.id] = { count: line.countedQuantity === null ? "" : String(line.countedQuantity), reason: line.reason }; }); setDrafts(next); }, [take.data]);
  const saveLine = async (line: StockTakeLine) => { const draft = drafts[line.id]; if (!draft || draft.count === "") return; setSaving(line.id); try { await api.put(`/stock-takes/${id}/items/${line.id}`, { countedQuantity: Number(draft.count), reason: draft.reason, version: line.version }); toast.success(`${line.name} counted`); take.reload(); onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not save count"); } finally { setSaving(null); } };
  const finalize = async () => { if (!take.data || !window.confirm("Finalize this count and apply every difference to inventory?")) return; try { await api.post(`/stock-takes/${id}/finalize`, { version: take.data.version }); toast.success("Stock take finalized"); take.reload(); onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not finalize count"); } };
  const cancel = async () => { if (!take.data || !window.confirm("Cancel this stock take? No inventory quantity will change.")) return; try { await api.post(`/stock-takes/${id}/cancel`, { version: take.data.version }); toast.success("Stock take cancelled"); take.reload(); onChanged(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Could not cancel count"); } };
  if (take.loading) return <DialogContent><Skeleton className="h-80" /></DialogContent>; if (take.error || !take.data) return <DialogContent><ErrorState message={take.error?.message ?? "Stock take unavailable"} retry={take.reload} /></DialogContent>;
  const value = take.data; const allCounted = value.items.every((line) => line.countedQuantity !== null); const editable = value.status === "in_progress";
  return <DialogContent className="max-w-4xl"><DialogHeader><DialogTitle className="font-mono">{value.stockTakeNumber}</DialogTitle><DialogDescription>{value.category.replaceAll("_", " ") || "All tracked inventory"} · started by {value.createdBy}</DialogDescription></DialogHeader><div className="flex items-center gap-2"><Badge tone={takeTone(value.status)}>{value.status.replaceAll("_", " ")}</Badge><span className="text-sm text-zinc-500">{value.items.filter((line) => line.countedQuantity !== null).length}/{value.items.length} counted</span></div><div className="max-h-[58vh] space-y-3 overflow-y-auto pr-1">{value.items.map((line) => { const draft = drafts[line.id] ?? { count: "", reason: "" }; const difference = draft.count === "" ? null : Number(draft.count) - line.expectedQuantity; return <div className="rounded-lg border p-3" key={line.id}><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{line.name}</div><div className="font-mono text-xs text-zinc-500">{line.sku} · expected {line.expectedQuantity}</div></div>{line.countedQuantity !== null && <Badge tone={line.difference === 0 ? "success" : "warning"}>{line.difference === 0 ? "Matched" : `${line.difference! > 0 ? "+" : ""}${line.difference}`}</Badge>}</div>{editable && <div className="mt-3 grid gap-3 sm:grid-cols-[130px_1fr_auto]"><Field label="Counted"><Input inputMode="numeric" type="number" min={0} value={draft.count} onChange={(event) => setDrafts({ ...drafts, [line.id]: { ...draft, count: event.target.value } })} /></Field><Field label="Difference reason"><Input required={difference !== null && difference !== 0} placeholder={difference === 0 ? "No difference" : "Required for a difference"} value={draft.reason} onChange={(event) => setDrafts({ ...drafts, [line.id]: { ...draft, reason: event.target.value } })} /></Field><div className="flex items-end"><Button className="w-full" size="sm" variant="outline" disabled={saving === line.id || draft.count === "" || (difference !== 0 && !draft.reason.trim())} onClick={() => saveLine(line)}>{saving === line.id ? "Saving…" : "Save"}</Button></div></div>}</div>; })}</div>{editable && user?.role === "doctor" && <DialogFooter><Button variant="outline" onClick={cancel}><XCircle className="h-4 w-4" />Cancel count</Button><Button disabled={!allCounted} onClick={finalize}><CheckCircle2 className="h-4 w-4" />Finalize & adjust</Button></DialogFooter>}{!editable && <div className="rounded-md bg-zinc-50 p-3 text-sm"><ClipboardCheck className="mr-2 inline h-4 w-4" />This stock take is locked and retained for audit.</div>}</DialogContent>;
}
